const LOBBY_CSS = `
:root {
  --lobby-ink: #151812;
  --lobby-night: #111a1b;
  --lobby-night-soft: #263536;
  --lobby-paper: #eee4c7;
  --lobby-paper-dim: #cbbd98;
  --lobby-moss: #788849;
  --lobby-moss-bright: #b5c675;
  --lobby-sun: #e6aa4e;
  --lobby-rust: #a55432;
  --lobby-display: Impact, Haettenschweiler, "Franklin Gothic Condensed", sans-serif;
  --lobby-copy: "Courier New", Courier, monospace;
}
* { box-sizing: border-box; }
.lc-lobby-shell { background: var(--lobby-night); color: var(--lobby-paper); font-family: var(--lobby-copy); height: 100%; min-height: 650px; overflow: auto; position: relative; width: 100%; }
.lc-lobby-shell button, .lc-lobby-shell input { font: inherit; }
.lc-lobby-panorama { background: linear-gradient(#1e3b43 0%, #587061 54%, #9d8a5a 77%, #292d21 78%); inset: 0; overflow: hidden; position: fixed; }
.lc-lobby-panorama::after { background: linear-gradient(90deg, rgba(12,19,18,.7), transparent 30%, transparent 68%, rgba(12,19,18,.62)), linear-gradient(0deg, rgba(10,14,12,.64), transparent 55%); content: ""; inset: 0; position: absolute; }
.lc-lobby-sky-grain { background-image: repeating-linear-gradient(0deg, rgba(255,255,255,.025) 0 1px, transparent 1px 4px); inset: 0; mix-blend-mode: overlay; opacity: .6; position: absolute; }
.lc-lobby-orb { background: #e3b15e; box-shadow: 0 0 80px rgba(230,170,78,.42); height: 10vw; min-height: 92px; min-width: 92px; position: absolute; right: 17%; top: 12%; width: 10vw; }
.lc-lobby-cloud { background: rgba(216,221,196,.13); box-shadow: 45px -15px rgba(216,221,196,.09), 96px 7px rgba(216,221,196,.12); height: 22px; position: absolute; width: 105px; }
.lc-lobby-cloud.is-one { animation: lc-lobby-drift 38s linear infinite; left: 12%; top: 17%; }.lc-lobby-cloud.is-two { animation: lc-lobby-drift 52s linear infinite reverse; right: 32%; top: 29%; transform: scale(.7); }
@keyframes lc-lobby-drift { 50% { transform: translateX(60px); } }
.lc-lobby-range { bottom: 22%; clip-path: polygon(0 66%, 7% 52%, 13% 59%, 21% 30%, 29% 55%, 36% 19%, 43% 49%, 54% 10%, 61% 42%, 68% 30%, 74% 54%, 83% 21%, 91% 50%, 100% 36%, 100% 100%, 0 100%); left: -3%; position: absolute; width: 106%; }
.lc-lobby-range.is-back { background: #40574e; height: 45%; opacity: .72; }.lc-lobby-range.is-mid { background: #263a32; bottom: 14%; height: 40%; transform: scaleX(1.12) translateX(-2%); }
.lc-lobby-ground { background: repeating-linear-gradient(90deg, #1a251c 0 12vw, #202b1f 12vw 23vw, #172118 23vw 35vw); bottom: -5%; height: 31%; left: -2%; position: absolute; transform: skewY(-2deg); width: 104%; }
.lc-lobby-tree { background: #342a1d; bottom: 18%; height: 16%; position: absolute; width: 20px; }.lc-lobby-tree::before, .lc-lobby-tree::after { background: #253e2c; content: ""; position: absolute; }.lc-lobby-tree::before { height: 82px; left: -45px; top: -60px; width: 104px; }.lc-lobby-tree::after { background: #304c31; height: 47px; left: -65px; top: -31px; width: 140px; }
.lc-lobby-tree.is-one { left: 7%; transform: scale(1.25); }.lc-lobby-tree.is-two { bottom: 16%; right: 6%; transform: scale(1.65); }.lc-lobby-tree.is-three { bottom: 20%; opacity: .74; right: 24%; transform: scale(.8); }
.lc-lobby-cube { background: #526638; border-top: 9px solid #78924c; bottom: 9%; box-shadow: inset -12px -12px rgba(0,0,0,.2), 0 18px 30px rgba(0,0,0,.22); height: 74px; position: absolute; transform: rotate(5deg); width: 74px; }.lc-lobby-cube.is-one { left: 19%; }.lc-lobby-cube.is-two { bottom: 4%; right: 17%; transform: rotate(-8deg) scale(.72); }
.lc-lobby-content { display: flex; flex-direction: column; margin: 0 auto; min-height: 100%; padding: 38px clamp(24px, 5vw, 76px) 24px; position: relative; width: min(1320px, 100%); z-index: 2; }
.lc-lobby-title { align-self: center; animation: lc-lobby-rise .55s cubic-bezier(.2,.8,.2,1) both; margin-bottom: 27px; text-align: center; }
@keyframes lc-lobby-rise { from { opacity: 0; transform: translateY(17px); } }
.lc-lobby-title > p { align-items: center; color: rgba(238,228,199,.58); display: flex; font-size: 9px; gap: 12px; justify-content: center; letter-spacing: .18em; margin: 0 0 10px; text-transform: uppercase; }.lc-lobby-title > p span { background: var(--lobby-sun); height: 1px; width: 32px; }
.lc-lobby-title h1 { filter: drop-shadow(0 13px 12px rgba(0,0,0,.35)); font-family: var(--lobby-display); font-size: clamp(69px, 9.5vw, 128px); letter-spacing: -.045em; line-height: .72; margin: 0; text-transform: uppercase; transform: scaleX(1.04); }
.lc-lobby-title h1 span:first-child { color: #dbe5b3; text-shadow: 0 2px #aab778, 0 4px #8b965f, 0 6px #657044, 0 8px #4c5535, 4px 10px #29301e; }.lc-lobby-title h1 span:last-child { color: #f1dfae; text-shadow: 0 2px #c4a96a, 0 4px #9f824c, 0 6px #795f35, 0 8px #594425, 4px 10px #2b261a; }
.lc-lobby-title > small { color: rgba(238,228,199,.75); display: block; font-size: 9px; letter-spacing: .12em; margin-top: 19px; text-transform: uppercase; }
.lc-lobby-grid { align-items: stretch; display: grid; gap: 15px; grid-template-columns: minmax(270px, .78fr) minmax(510px, 1.45fr); margin: auto 0; }
.lc-lobby-account, .lc-lobby-world-card { animation: lc-lobby-rise .5s .12s cubic-bezier(.2,.8,.2,1) both; backdrop-filter: blur(10px); border: 1px solid rgba(238,228,199,.23); box-shadow: 0 22px 60px rgba(0,0,0,.29); }
.lc-lobby-account { background: rgba(17,25,23,.91); min-height: 306px; padding: 23px; }
.lc-lobby-panel-head { align-items: center; border-bottom: 1px solid rgba(238,228,199,.13); display: grid; gap: 12px; grid-template-columns: auto 1fr auto; padding-bottom: 17px; }.lc-lobby-panel-index { color: rgba(238,228,199,.25); font-size: 24px; font-weight: bold; }.lc-lobby-eyebrow { color: var(--lobby-sun); font-size: 8px; letter-spacing: .16em; margin: 0 0 4px; text-transform: uppercase; }.lc-lobby-panel-head h2, .lc-lobby-world-body h2 { font-family: var(--lobby-display); font-size: 23px; letter-spacing: .025em; line-height: 1; margin: 0; text-transform: uppercase; }
.lc-lobby-auth-light { background: #65706b; border-radius: 50%; box-shadow: 0 0 0 4px rgba(101,112,107,.12); height: 8px; width: 8px; }.lc-lobby-auth-light.is-ready { background: var(--lobby-moss-bright); box-shadow: 0 0 0 4px rgba(181,198,117,.12); }.lc-lobby-auth-light.is-needs_username { background: var(--lobby-sun); }
.lc-lobby-account-loading { display: grid; gap: 8px; padding-top: 31px; }.lc-lobby-account-loading span { animation: lc-lobby-pulse 1s infinite alternate; background: rgba(238,228,199,.08); height: 17px; }.lc-lobby-account-loading span:nth-child(2) { animation-delay: .25s; width: 67%; }.lc-lobby-account-loading small { color: rgba(238,228,199,.45); font-size: 9px; margin-top: 12px; }
@keyframes lc-lobby-pulse { to { background: rgba(238,228,199,.16); } }
.lc-lobby-signin { padding-top: 24px; }.lc-lobby-signin p { color: rgba(238,228,199,.75); font-size: 11px; line-height: 1.65; margin: 0 0 18px; }.lc-lobby-google { align-items: center; background: var(--lobby-paper); border: 0; color: var(--lobby-ink); cursor: pointer; display: grid; font-size: 10px; font-weight: bold; gap: 10px; grid-template-columns: auto 1fr auto; letter-spacing: .07em; padding: 10px; text-align: left; text-transform: uppercase; transition: background .15s, transform .15s; width: 100%; }.lc-lobby-google:hover { background: #fff7df; transform: translateY(-2px); }.lc-lobby-google:focus-visible, .lc-lobby-join:focus-visible, .lc-lobby-footer button:focus-visible, .lc-lobby-text-button:focus-visible, .lc-lobby-username input:focus-visible, .lc-lobby-username button:focus-visible { outline: 2px solid var(--lobby-sun); outline-offset: 3px; }.lc-lobby-google-mark { align-items: center; background: #fff; border: 1px solid rgba(0,0,0,.15); display: flex; font-family: Georgia, serif; font-size: 15px; height: 28px; justify-content: center; width: 28px; }.lc-lobby-signin small { color: rgba(238,228,199,.4); display: block; font-size: 8px; line-height: 1.5; margin-top: 12px; }
.lc-lobby-username { padding-top: 26px; }.lc-lobby-username label { display: block; font-size: 10px; font-weight: bold; letter-spacing: .04em; margin-bottom: 10px; }.lc-lobby-username-row { background: rgba(238,228,199,.08); border: 1px solid rgba(238,228,199,.21); display: grid; grid-template-columns: auto minmax(0,1fr) auto; }.lc-lobby-username-row > span { align-self: center; color: var(--lobby-sun); padding-left: 11px; }.lc-lobby-username input { background: transparent; border: 0; color: var(--lobby-paper); font-size: 13px; min-width: 0; outline: 0; padding: 13px 8px; }.lc-lobby-username input::placeholder { color: rgba(238,228,199,.28); }.lc-lobby-username button { background: var(--lobby-moss); border: 0; color: #fffbe9; cursor: pointer; font-size: 9px; font-weight: bold; letter-spacing: .07em; margin: 4px; padding: 0 13px; text-transform: uppercase; }.lc-lobby-username button:disabled { cursor: not-allowed; filter: grayscale(.7); opacity: .5; }.lc-lobby-username-status { font-size: 8px; line-height: 1.5; margin: 9px 0 0; min-height: 24px; }.lc-lobby-username-status.is-quiet { color: rgba(238,228,199,.42); }.lc-lobby-username-status.is-good { color: var(--lobby-moss-bright); }.lc-lobby-username-status.is-busy { color: var(--lobby-sun); }.lc-lobby-username-status.is-bad { color: #efa584; }
.lc-lobby-profile { align-items: center; display: grid; gap: 13px; grid-template-columns: auto 1fr auto; padding-top: 24px; }.lc-lobby-avatar { background: #b9815b; box-shadow: inset -8px -8px rgba(0,0,0,.13); height: 54px; position: relative; width: 54px; }.lc-lobby-avatar-hair { background: #3d2b22; height: 15px; left: 0; position: absolute; right: 0; top: 0; }.lc-lobby-avatar-hair::after { background: #3d2b22; content: ""; height: 9px; position: absolute; right: 0; top: 10px; width: 9px; }.lc-lobby-avatar-eye { background: #e9f2da; height: 5px; position: absolute; top: 27px; width: 9px; }.lc-lobby-avatar-eye::after { background: #3a6065; content: ""; height: 5px; position: absolute; width: 4px; }.lc-lobby-avatar-eye.is-left { left: 9px; }.lc-lobby-avatar-eye.is-right { right: 9px; }.lc-lobby-profile-copy > span { color: rgba(238,228,199,.43); display: block; font-size: 8px; letter-spacing: .08em; text-transform: uppercase; }.lc-lobby-profile-copy strong { display: block; font-family: var(--lobby-display); font-size: 22px; letter-spacing: .03em; margin: 3px 0; text-transform: uppercase; }.lc-lobby-profile-copy small { color: rgba(238,228,199,.48); display: block; font-size: 8px; max-width: 145px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.lc-lobby-text-button { background: none; border: 0; color: rgba(238,228,199,.45); cursor: pointer; font-size: 8px; padding: 8px 0; text-decoration: underline; text-underline-offset: 3px; }
.lc-lobby-world-card { animation-delay: .2s; background: rgba(235,225,194,.96); color: var(--lobby-ink); display: grid; grid-template-columns: minmax(190px, .52fr) minmax(330px, 1fr); }
.lc-lobby-world-thumb { background: linear-gradient(#5d8077 0 44%, #809060 44% 57%, #425030 57%); min-height: 306px; overflow: hidden; position: relative; }.lc-lobby-world-thumb::after { background: linear-gradient(90deg, transparent, rgba(0,0,0,.22)), repeating-linear-gradient(0deg, rgba(255,255,255,.025) 0 1px, transparent 1px 4px); content: ""; inset: 0; position: absolute; }.lc-lobby-world-sun { background: #edc46d; height: 48px; position: absolute; right: 16%; top: 13%; width: 48px; }.lc-lobby-world-hill { bottom: 36%; clip-path: polygon(0 100%, 19% 28%, 39% 67%, 57% 8%, 71% 56%, 89% 28%, 100% 59%, 100% 100%); left: -5%; position: absolute; width: 110%; }.lc-lobby-world-hill.is-far { background: #506853; height: 44%; }.lc-lobby-world-hill.is-near { background: #334a35; bottom: 30%; height: 38%; transform: translateX(18%); }.lc-lobby-world-tree { background: #4c3625; bottom: 18%; height: 28%; left: 17%; position: absolute; width: 17px; }.lc-lobby-world-tree::before { background: #375534; box-shadow: 22px 12px #2e492f, -18px 21px #3f5f39; content: ""; height: 58px; left: -25px; position: absolute; top: -37px; width: 67px; }.lc-lobby-world-player { background: #4d7b75; bottom: 19%; height: 48px; position: absolute; right: 19%; width: 20px; }.lc-lobby-world-player::before { background: #a87755; content: ""; height: 19px; left: -2px; position: absolute; top: -18px; width: 24px; }.lc-lobby-world-player::after { background: #27342d; bottom: -19px; box-shadow: 13px 0 #27342d; content: ""; height: 22px; left: 1px; position: absolute; width: 7px; }
.lc-lobby-world-body { padding: 23px 25px 20px; }.lc-lobby-world-body header { align-items: flex-start; display: flex; justify-content: space-between; }.lc-lobby-world-body .lc-lobby-eyebrow { color: var(--lobby-rust); }.lc-lobby-world-body h2 { font-size: 32px; }.lc-lobby-server-state { align-items: center; display: flex; font-size: 8px; gap: 7px; letter-spacing: .08em; text-transform: uppercase; }.lc-lobby-server-state span { background: #8d7457; border-radius: 50%; height: 7px; width: 7px; }.lc-lobby-server-state.is-online span { background: var(--lobby-moss); box-shadow: 0 0 0 4px rgba(120,136,73,.14); }.lc-lobby-server-state.is-busy span { background: var(--lobby-sun); }.lc-lobby-server-state.is-offline span, .lc-lobby-server-state.is-maintenance span { background: var(--lobby-rust); }.lc-lobby-world-body > p { color: rgba(21,24,18,.65); font-size: 9px; line-height: 1.55; margin: 13px 0 17px; }.lc-lobby-world-body dl { border-bottom: 1px solid rgba(21,24,18,.15); border-top: 1px solid rgba(21,24,18,.15); display: grid; grid-template-columns: repeat(3,1fr); margin: 0 0 15px; padding: 10px 0; }.lc-lobby-world-body dl > div + div { border-left: 1px solid rgba(21,24,18,.12); padding-left: 12px; }.lc-lobby-world-body dt { color: rgba(21,24,18,.43); font-size: 7px; letter-spacing: .1em; text-transform: uppercase; }.lc-lobby-world-body dd { font-size: 9px; font-weight: bold; margin: 4px 0 0; }
.lc-lobby-join { align-items: center; background: var(--lobby-ink); border: 0; box-shadow: 5px 5px 0 rgba(120,136,73,.55); color: var(--lobby-paper); cursor: pointer; display: flex; font-family: var(--lobby-display); font-size: 16px; justify-content: space-between; letter-spacing: .07em; padding: 12px 14px; text-transform: uppercase; transition: background .15s, box-shadow .15s, transform .15s; width: 100%; }.lc-lobby-join:not(:disabled):hover { background: var(--lobby-moss); box-shadow: 2px 2px 0 rgba(21,24,18,.8); transform: translate(3px,3px); }.lc-lobby-join:disabled { cursor: not-allowed; filter: saturate(.4); opacity: .58; }.lc-lobby-join kbd { color: var(--lobby-paper-dim); font: 8px var(--lobby-copy); }.lc-lobby-wait { align-items: center; display: flex; gap: 8px; margin-top: 9px; }.lc-lobby-wait span { animation: lc-lobby-spin 1s steps(4) infinite; border: 2px solid rgba(21,24,18,.18); border-top-color: var(--lobby-moss); height: 11px; width: 11px; }.lc-lobby-wait p, .lc-lobby-join-error { font-size: 8px !important; margin: 0 !important; }.lc-lobby-join-error { color: var(--lobby-rust) !important; padding-top: 8px; }
@keyframes lc-lobby-spin { to { transform: rotate(360deg); } }
.lc-lobby-footer { align-items: center; display: flex; justify-content: space-between; margin-top: 25px; }.lc-lobby-footer nav { display: flex; gap: 7px; }.lc-lobby-footer button { background: rgba(17,25,23,.74); border: 1px solid rgba(238,228,199,.17); color: rgba(238,228,199,.72); cursor: pointer; font-size: 8px; padding: 8px 10px; }.lc-lobby-footer button:hover { background: rgba(17,25,23,.95); color: var(--lobby-paper); }.lc-lobby-footer button kbd { color: var(--lobby-sun); margin-left: 8px; }.lc-lobby-footer > p { align-items: center; color: rgba(238,228,199,.52); display: flex; font-size: 8px; gap: 7px; margin: 0; }.lc-lobby-footer > p small { border: 1px solid rgba(238,228,199,.25); font-size: 7px; margin-left: 7px; padding: 3px 5px; }.lc-lobby-live-dot { background: var(--lobby-moss-bright); border-radius: 50%; height: 6px; width: 6px; }
@media (max-width: 900px) { .lc-lobby-shell { min-height: 780px; }.lc-lobby-grid { grid-template-columns: 1fr; }.lc-lobby-account { min-height: 0; }.lc-lobby-world-card { grid-template-columns: 160px 1fr; }.lc-lobby-world-thumb { min-height: 290px; }.lc-lobby-content { padding-top: 28px; }.lc-lobby-title h1 { font-size: 76px; } }
@media (max-width: 620px) { .lc-lobby-shell { min-height: 920px; }.lc-lobby-content { padding: 24px 14px 18px; }.lc-lobby-title { margin-bottom: 20px; }.lc-lobby-title h1 { font-size: 60px; }.lc-lobby-world-card { display: block; }.lc-lobby-world-thumb { min-height: 155px; }.lc-lobby-world-body h2 { font-size: 27px; }.lc-lobby-world-body dl { grid-template-columns: 1fr 1fr; }.lc-lobby-world-body dl > div:last-child { display: none; }.lc-lobby-footer { align-items: flex-start; flex-direction: column; gap: 13px; }.lc-lobby-footer nav { flex-wrap: wrap; }.lc-lobby-footer > p { line-height: 1.4; }.lc-lobby-cube, .lc-lobby-tree.is-three { display: none; } }
@media (prefers-reduced-motion: reduce) { .lc-lobby-cloud, .lc-lobby-account-loading span, .lc-lobby-wait span, .lc-lobby-title, .lc-lobby-account, .lc-lobby-world-card { animation: none; }.lc-lobby-google, .lc-lobby-join { transition: none; } }
`;

export function LobbyStyles() {
  return <style>{LOBBY_CSS}</style>;
}
