const CHAT_CSS = `
:root { --chat-ink: #171a16; --chat-paper: #eee4c7; --chat-moss: #788849; --chat-amber: #e0a24d; --chat-rust: #ac5b3a; --chat-note: "Courier New", Courier, monospace; --chat-display: "Trebuchet MS", "Avenir Next Condensed", sans-serif; }
.lc-chat-dialog, .lc-chat-peek { color: var(--chat-paper); font-family: var(--chat-note); position: fixed; z-index: 48; }
.lc-chat-dialog *, .lc-chat-peek * { box-sizing: border-box; }.lc-chat-dialog button, .lc-chat-dialog input, .lc-chat-peek button { font: inherit; }
.lc-chat-dialog { animation: lc-chat-open .18s ease-out both; background: rgba(19,23,18,.94); border: 1px solid rgba(238,228,199,.24); bottom: 92px; box-shadow: 8px 11px 0 rgba(0,0,0,.17), 0 22px 60px rgba(0,0,0,.38); display: grid; grid-template-rows: auto minmax(110px, 1fr) auto; left: 20px; max-height: min(520px, calc(100vh - 160px)); min-height: 330px; width: min(480px, calc(100vw - 40px)); }
@keyframes lc-chat-open { from { opacity: 0; transform: translateY(9px); } }
.lc-chat-dialog::before { background: var(--chat-amber); content: ""; height: 3px; left: -1px; position: absolute; top: -1px; width: 76px; }
.lc-chat-dialog > header { align-items: center; border-bottom: 1px solid rgba(238,228,199,.13); display: flex; justify-content: space-between; min-height: 55px; padding: 10px 12px 10px 15px; }.lc-chat-dialog > header > div { align-items: center; display: grid; gap: 0 9px; grid-template-columns: auto 1fr; }.lc-chat-dialog > header strong { font-family: var(--chat-display); font-size: 13px; grid-column: 2; letter-spacing: .09em; text-transform: uppercase; }.lc-chat-dialog > header small { color: rgba(238,228,199,.42); font-size: 7px; grid-column: 2; letter-spacing: .08em; margin-top: 2px; text-transform: uppercase; }
.lc-chat-signal { background: var(--chat-rust); border-radius: 50%; grid-row: 1 / 3; height: 7px; width: 7px; }.lc-chat-signal.is-connected { animation: lc-chat-signal 2s ease-out infinite; background: #acc06e; box-shadow: 0 0 0 1px #acc06e; }@keyframes lc-chat-signal { 70%,100% { box-shadow: 0 0 0 7px rgba(172,192,110,0); } }
.lc-chat-close { align-items: center; background: none; border: 0; color: rgba(238,228,199,.48); cursor: pointer; display: flex; font-size: 7px; gap: 8px; padding: 5px; text-transform: uppercase; }.lc-chat-close:hover { color: var(--chat-paper); }.lc-chat-close kbd { border: 1px solid rgba(238,228,199,.25); color: var(--chat-paper); padding: 4px 5px; }
.lc-chat-history { display: flex; flex-direction: column; gap: 3px; list-style: none; margin: 0; overflow-y: auto; overscroll-behavior: contain; padding: 8px 9px; scrollbar-color: rgba(238,228,199,.23) transparent; }.lc-chat-message { border-left: 2px solid rgba(238,228,199,.12); padding: 7px 10px 8px; }.lc-chat-message:hover { background: rgba(238,228,199,.035); border-left-color: rgba(238,228,199,.28); }.lc-chat-message.is-own { border-left-color: var(--chat-moss); }.lc-chat-message.is-system { background: rgba(224,162,77,.06); border-left-color: var(--chat-amber); }.lc-chat-message.is-warning, .lc-chat-message.is-failed { border-left-color: var(--chat-rust); }.lc-chat-message.is-sending { opacity: .56; }
.lc-chat-message-meta { align-items: center; display: flex; gap: 8px; }.lc-chat-message-meta strong { color: #b7c979; font-family: var(--chat-display); font-size: 9px; letter-spacing: .06em; max-width: 230px; overflow: hidden; text-overflow: ellipsis; text-transform: uppercase; white-space: nowrap; }.lc-chat-message.is-system .lc-chat-message-meta strong { color: var(--chat-amber); }.lc-chat-message-meta time { color: rgba(238,228,199,.29); font-size: 7px; }.lc-chat-message p { color: rgba(238,228,199,.9); font-size: 10px; line-height: 1.45; margin: 3px 0 0; overflow-wrap: anywhere; white-space: pre-wrap; }.lc-chat-message > small { color: rgba(238,228,199,.35); display: block; font-size: 7px; margin-top: 3px; }.lc-chat-message > button { background: none; border: 0; color: #e89372; cursor: pointer; font-size: 7px; margin-top: 3px; padding: 0; text-decoration: underline; text-underline-offset: 2px; }
.lc-chat-empty { align-items: center; color: rgba(238,228,199,.35); display: flex; flex-direction: column; margin: auto; padding: 30px; text-align: center; }.lc-chat-empty > span { color: var(--chat-moss); font-size: 32px; }.lc-chat-empty strong { color: rgba(238,228,199,.58); font-family: var(--chat-display); font-size: 14px; letter-spacing: .06em; margin: 7px 0 3px; text-transform: uppercase; }.lc-chat-empty small { font-size: 8px; }
.lc-chat-compose { border-top: 1px solid rgba(238,228,199,.14); padding: 10px; }.lc-chat-compose > label { clip: rect(0 0 0 0); clip-path: inset(50%); height: 1px; overflow: hidden; position: absolute; white-space: nowrap; width: 1px; }.lc-chat-compose > div { align-items: center; background: rgba(238,228,199,.08); border: 1px solid rgba(238,228,199,.18); display: grid; grid-template-columns: auto minmax(0,1fr) auto auto; }.lc-chat-compose > div:focus-within { border-color: var(--chat-amber); box-shadow: 0 0 0 1px var(--chat-amber); }.lc-chat-compose > div > span { color: var(--chat-amber); font-size: 17px; padding-left: 10px; }.lc-chat-compose input { background: none; border: 0; color: var(--chat-paper); font-size: 10px; min-width: 0; outline: 0; padding: 12px 8px; }.lc-chat-compose input::placeholder { color: rgba(238,228,199,.3); }.lc-chat-compose input:disabled { cursor: wait; }.lc-chat-compose > div > small { color: rgba(238,228,199,.28); font-size: 7px; }.lc-chat-compose > div > small.is-limit { color: #e89372; }.lc-chat-compose button { align-items: center; align-self: stretch; background: var(--chat-moss); border: 0; color: #fffbe9; cursor: pointer; display: flex; font-family: var(--chat-display); font-size: 9px; gap: 8px; letter-spacing: .08em; margin-left: 9px; padding: 0 11px; text-transform: uppercase; }.lc-chat-compose button:disabled { cursor: not-allowed; filter: grayscale(.8); opacity: .38; }.lc-chat-compose button kbd { font: 10px var(--chat-note); }.lc-chat-compose > small, .lc-chat-compose > p { color: rgba(238,228,199,.34); display: block; font-size: 7px; margin: 7px 2px 0; }.lc-chat-compose > p { color: #e89372; }
.lc-chat-peek { bottom: 103px; left: 20px; pointer-events: none; width: min(420px, calc(100vw - 40px)); }.lc-chat-peek ol { display: flex; flex-direction: column; gap: 4px; list-style: none; margin: 0 0 7px; padding: 0; }.lc-chat-peek ol li { animation: lc-chat-peek-in .2s ease-out both; background: rgba(16,20,15,.64); border-left: 2px solid rgba(181,198,117,.58); display: flex; font-size: 9px; gap: 8px; line-height: 1.35; max-width: max-content; padding: 5px 8px; text-shadow: 0 1px 2px #000; }.lc-chat-peek ol strong { color: #c6d78c; flex: none; font-family: var(--chat-display); font-size: 8px; letter-spacing: .04em; text-transform: uppercase; }.lc-chat-peek ol span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.lc-chat-peek > button { align-items: center; background: rgba(17,22,17,.84); border: 1px solid rgba(238,228,199,.21); color: var(--chat-paper); cursor: pointer; display: flex; font-family: var(--chat-display); font-size: 9px; gap: 8px; letter-spacing: .09em; padding: 6px 8px; pointer-events: auto; text-transform: uppercase; }.lc-chat-peek > button:hover { background: rgba(17,22,17,.97); border-color: rgba(238,228,199,.4); }.lc-chat-peek > button > span:first-child { align-items: center; border: 1px solid rgba(238,228,199,.32); display: flex; font: 8px var(--chat-note); height: 18px; justify-content: center; width: 18px; }.lc-chat-peek > button b { background: var(--chat-rust); border-radius: 7px; font: 7px var(--chat-note); min-width: 14px; padding: 2px 4px; }
@keyframes lc-chat-peek-in { from { opacity: 0; transform: translateX(-6px); } }
.lc-chat-close:focus-visible, .lc-chat-compose input:focus-visible, .lc-chat-compose button:focus-visible, .lc-chat-peek > button:focus-visible, .lc-chat-message > button:focus-visible { outline: 2px solid var(--chat-amber); outline-offset: 2px; }
@media (max-width: 620px) { .lc-chat-dialog { bottom: 10px; left: 10px; max-height: calc(100vh - 20px); min-height: min(430px, calc(100vh - 20px)); width: calc(100vw - 20px); }.lc-chat-peek { bottom: 86px; left: 10px; width: calc(100vw - 20px); } }
@media (prefers-reduced-motion: reduce) { .lc-chat-dialog, .lc-chat-signal.is-connected, .lc-chat-peek ol li { animation: none; } }
`;

export function ChatStyles() {
  return <style>{CHAT_CSS}</style>;
}
