const HUD_CSS = `
:root {
  --lc-paper: #e6dcc1;
  --lc-paper-deep: #c9b98f;
  --lc-ink: #24261f;
  --lc-charcoal: #171a16;
  --lc-moss: #667541;
  --lc-moss-bright: #a8b66b;
  --lc-amber: #d49a45;
  --lc-rust: #9a5434;
  --lc-line: rgba(33, 37, 29, .2);
  --lc-shadow: rgba(10, 12, 9, .45);
  --lc-pixel-font: "Pixelify Sans", "Courier New", Courier, monospace;
  --lc-display: var(--lc-pixel-font);
  --lc-note: var(--lc-pixel-font);
}
.lc-hud, .lc-drawer-layer, .lc-unsupported, .lc-menu-layer, .lc-death-layer { color: var(--lc-paper); font-family: var(--lc-pixel-font); image-rendering: pixelated; }
.lc-hud { height: 100vh; height: 100dvh; inset: 0 auto auto 0; overflow: hidden; pointer-events: none; position: fixed; width: 100vw; z-index: 20; }
.lc-hud button, .lc-drawer-layer button, .lc-unsupported button, .lc-menu-layer button, .lc-death-layer button { font: inherit; }
.lc-kicker { color: var(--lc-amber); font: 9px/1.2 var(--lc-note); letter-spacing: .14em; text-transform: uppercase; }
.lc-crosshair { height: 16px; left: 50%; pointer-events: none; position: absolute; top: 50%; transform: translate(-50%,-50%); width: 16px; z-index: 3; }
.lc-crosshair::before,.lc-crosshair::after { content: ""; inset: 0; position: absolute; }
.lc-crosshair::before { background: #111; clip-path: polygon(6px 0,10px 0,10px 6px,16px 6px,16px 10px,10px 10px,10px 16px,6px 16px,6px 10px,0 10px,0 6px,6px 6px); }.lc-crosshair::after { background: #fff; clip-path: polygon(7px 1px,9px 1px,9px 7px,15px 7px,15px 9px,9px 9px,9px 15px,7px 15px,7px 9px,1px 9px,1px 7px,7px 7px); }
.lc-first-person { bottom: -72px; height: clamp(272px,32vw,372px); position: absolute; right: -16px; width: clamp(250px,30vw,372px); z-index: 1; }
.lc-first-person__rig { display: block; height: 100%; position: relative; transform: translate3d(0,0,0) rotateZ(-2deg); transform-origin: 91% 96%; transform-style: preserve-3d; width: 100%; }
.lc-first-person__rig.is-swinging { animation: lc-held-item-swing 220ms cubic-bezier(.2,.72,.24,1) both; }
.lc-first-person__arm-scene { bottom: -1%; height: 86%; perspective: 620px; perspective-origin: 72% 42%; position: absolute; right: -1%; width: 48%; z-index: 1; }
.lc-first-person__arm { bottom: -8%; height: 104%; position: absolute; right: 10%; transform: rotateZ(-28deg) rotateX(-6deg) rotateY(20deg); transform-origin: 50% 100%; transform-style: preserve-3d; width: 45%; }
.lc-first-person__arm-segment { --lc-arm-front: #b97855; --lc-arm-side: #754531; --lc-arm-top: #dda078; bottom: 0; display: block; height: 48%; left: 0; position: absolute; transform-style: preserve-3d; width: 100%; }
.lc-first-person__arm-segment--sleeve { --lc-arm-front: #24969b; --lc-arm-side: #125963; --lc-arm-top: #47b8b5; height: 58%; }
.lc-first-person__arm-segment--skin { bottom: 55%; height: 39%; }
.lc-first-person__arm-face { backface-visibility: hidden; box-sizing: border-box; display: block; image-rendering: pixelated; position: absolute; }
.lc-first-person__arm-face--front { background-color: var(--lc-arm-front); background-image: linear-gradient(90deg,rgba(255,255,255,.07) 0 16%,transparent 16% 79%,rgba(0,0,0,.13) 79%); height: 100%; inset: 0; transform: translateZ(9px); width: 100%; }
.lc-first-person__arm-face--left { background: var(--lc-arm-side); height: 100%; left: -18px; transform: rotateY(-90deg); transform-origin: right center; width: 18px; }
.lc-first-person__arm-face--top { background: var(--lc-arm-top); height: 18px; left: 0; top: -18px; transform: rotateX(90deg); transform-origin: bottom center; width: 100%; }
.lc-first-person__arm-segment--sleeve .lc-first-person__arm-face--front { background-image: linear-gradient(90deg,rgba(72,193,190,.34) 0 16%,transparent 16% 74%,rgba(5,63,70,.32) 74%),linear-gradient(0deg,transparent 0 62%,rgba(83,204,198,.24) 62% 78%,transparent 78%); }
.lc-first-person__arm-segment--skin .lc-first-person__arm-face--front { background-image: linear-gradient(90deg,#c98661 0 15%,transparent 15% 78%,rgba(87,45,31,.24) 78%),linear-gradient(0deg,transparent 0 26%,rgba(224,157,116,.55) 26% 39%,transparent 39% 68%,rgba(126,70,48,.25) 68% 78%,transparent 78%); }
.lc-first-person__item { bottom: 40%; height: clamp(104px,13vw,150px); position: absolute; right: 23%; transform: rotate(-18deg); transform-origin: 70% 78%; width: clamp(104px,13vw,150px); z-index: 2; }
.lc-held-sprite { display: block; height: 100%; position: relative; transform: rotateX(7deg) rotateY(-9deg); transform-origin: 70% 78%; transform-style: preserve-3d; width: 100%; }
.lc-held-sprite__slice { filter: brightness(.38) saturate(.76); inset: 0; position: absolute; transform: translate(var(--lc-held-sprite-offset),var(--lc-held-sprite-offset)); }
.lc-held-sprite__slice.is-front { filter: drop-shadow(6px 8px 0 rgba(0,0,0,.3)); }
.lc-held-sprite__slice .lc-item-glyph,.lc-held-sprite__slice .lc-item-icon__svg,.lc-held-sprite__slice .lc-item-glyph--block .lc-item-icon__svg { height: 100%; width: 100%; }
.lc-first-person[data-held-mode="voxel"] .lc-first-person__item { bottom: 31%; height: clamp(140px,17vw,190px); right: 16%; transform: rotate(-5deg); width: clamp(140px,17vw,190px); }
.lc-first-person[data-held-family="tool"] .lc-first-person__item { bottom: 40%; right: 23%; transform: rotate(-23deg) scale(1.06); }
.lc-first-person[data-held-family="food"] .lc-first-person__item,.lc-first-person[data-held-family="material"] .lc-first-person__item { bottom: 44%; right: 22%; transform: rotate(-11deg) scale(.84); }
.lc-first-person__item [data-icon-variant="stone_brick_slab"] { transform: scale(1.08) translateY(8%); transform-origin: 50% 72%; }
.lc-held-voxel { --lc-held-cube-size: clamp(80px,11vw,118px); display: block; filter: drop-shadow(7px 10px 0 rgba(0,0,0,.28)); height: 100%; perspective: 420px; perspective-origin: 50% 40%; position: relative; width: 100%; }
.lc-held-voxel__cube { height: var(--lc-held-cube-size); left: 50%; position: absolute; top: 48%; transform: translate(-50%,-50%) rotateX(-24deg) rotateY(-34deg); transform-style: preserve-3d; width: var(--lc-held-cube-size); }
.lc-held-voxel__face { --lc-voxel-face: var(--lc-voxel-front); backface-visibility: hidden; background-color: var(--lc-voxel-face); border: 2px solid var(--lc-voxel-edge); box-shadow: inset 3px 3px rgba(255,255,255,.08),inset -4px -4px rgba(0,0,0,.14); box-sizing: border-box; display: block; height: 100%; image-rendering: pixelated; overflow: hidden; position: absolute; width: 100%; }
.lc-held-voxel__face::after { background: var(--lc-voxel-accent); box-shadow: calc(var(--lc-held-cube-size)*.29) calc(var(--lc-held-cube-size)*.11) 0 var(--lc-voxel-dark),calc(var(--lc-held-cube-size)*.57) calc(var(--lc-held-cube-size)*-.04) 0 var(--lc-voxel-accent),calc(var(--lc-held-cube-size)*.12) calc(var(--lc-held-cube-size)*.38) 0 var(--lc-voxel-dark),calc(var(--lc-held-cube-size)*.48) calc(var(--lc-held-cube-size)*.52) 0 var(--lc-voxel-accent),calc(var(--lc-held-cube-size)*.67) calc(var(--lc-held-cube-size)*.31) 0 var(--lc-voxel-dark); content: ""; height: calc(var(--lc-held-cube-size)*.075); left: 11%; position: absolute; top: 13%; width: calc(var(--lc-held-cube-size)*.1); }
.lc-held-voxel__face--front { transform: translateZ(calc(var(--lc-held-cube-size) / 2)); }.lc-held-voxel__face--right { --lc-voxel-face: var(--lc-voxel-right); transform: rotateY(90deg) translateZ(calc(var(--lc-held-cube-size) / 2)); }.lc-held-voxel__face--top { --lc-voxel-face: var(--lc-voxel-top); transform: rotateX(90deg) translateZ(calc(var(--lc-held-cube-size) / 2)); }
.lc-held-voxel[data-block="grass"] .lc-held-voxel__face:not(.lc-held-voxel__face--top) { background-image: linear-gradient(var(--lc-voxel-top) 0 15%,transparent 15%); }
.lc-held-voxel:is([data-block="coal_ore"],[data-block="iron_ore"],[data-block="gold_ore"],[data-block="diamond_ore"]) .lc-held-voxel__face { background-image: linear-gradient(135deg,transparent 0 37%,var(--lc-voxel-accent) 37% 54%,transparent 54%),linear-gradient(45deg,transparent 0 68%,var(--lc-voxel-dark) 68% 80%,transparent 80%); background-size: 33px 29px,41px 37px; }
.lc-held-voxel[data-block="log"] .lc-held-voxel__face:not(.lc-held-voxel__face--top) { background-image: repeating-linear-gradient(90deg,transparent 0 13px,var(--lc-voxel-dark) 13px 18px,transparent 18px 29px); }.lc-held-voxel[data-block="log"] .lc-held-voxel__face--top { background-image: repeating-radial-gradient(circle,var(--lc-voxel-accent) 0 8px,var(--lc-voxel-dark) 9px 12px,var(--lc-voxel-top) 13px 20px); }.lc-held-voxel[data-block="log"] .lc-held-voxel__face::after,.lc-held-voxel:is([data-block="planks"],[data-block="crafting_table"],[data-block="chest"]) .lc-held-voxel__face::after,.lc-held-voxel:is([data-block="stone"],[data-block="cobblestone"],[data-block="furnace"],[data-block="stone_bricks"],[data-block="clay"],[data-block="bricks"]) .lc-held-voxel__face::after,.lc-held-voxel[data-block="glass"] .lc-held-voxel__face::after { content: none; }
.lc-held-voxel:is([data-block="planks"],[data-block="crafting_table"],[data-block="chest"]) .lc-held-voxel__face { background-image: repeating-linear-gradient(0deg,transparent 0 19px,var(--lc-voxel-dark) 19px 23px),linear-gradient(90deg,transparent 0 47%,var(--lc-voxel-accent) 47% 52%,transparent 52%); background-size: auto,43px 46px; }
.lc-held-voxel:is([data-block="stone"],[data-block="cobblestone"],[data-block="furnace"]) .lc-held-voxel__face { background-image: linear-gradient(145deg,transparent 0 46%,var(--lc-voxel-dark) 46% 52%,transparent 52%),linear-gradient(35deg,transparent 0 68%,var(--lc-voxel-accent) 68% 74%,transparent 74%); background-size: 39px 31px,47px 43px; }
.lc-held-voxel:is([data-block="stone_bricks"],[data-block="bricks"]) .lc-held-voxel__face { background-image: linear-gradient(90deg,transparent 0 46%,var(--lc-voxel-dark) 46% 54%,transparent 54%),linear-gradient(90deg,transparent 0 46%,var(--lc-voxel-dark) 46% 54%,transparent 54%),repeating-linear-gradient(0deg,transparent 0 24px,var(--lc-voxel-dark) 24px 29px); background-position: 0 0,28px 29px,0 0; background-size: 56px 58px,56px 58px,auto; }
.lc-held-voxel[data-block="clay"] .lc-held-voxel__face { background-image: linear-gradient(8deg,transparent 0 46%,var(--lc-voxel-dark) 46% 51%,transparent 51%),linear-gradient(-12deg,transparent 0 69%,var(--lc-voxel-accent) 69% 74%,transparent 74%); background-size: 47px 37px,53px 43px; }
.lc-held-voxel[data-block="leaves"] .lc-held-voxel__face { background-image: linear-gradient(45deg,transparent 0 35%,var(--lc-voxel-accent) 35% 57%,transparent 57%),linear-gradient(135deg,transparent 0 61%,var(--lc-voxel-dark) 61% 76%,transparent 76%); background-size: 25px 27px,31px 33px; }
.lc-held-voxel[data-block="glass"] { filter: drop-shadow(5px 8px 0 rgba(0,0,0,.16)); }.lc-held-voxel[data-block="glass"] .lc-held-voxel__face { background-color: color-mix(in srgb,var(--lc-voxel-face) 45%,transparent); background-image: linear-gradient(135deg,transparent 0 22%,rgba(255,255,255,.72) 22% 28%,transparent 28% 68%,var(--lc-voxel-accent) 68% 74%,transparent 74%); box-shadow: inset 5px 5px rgba(255,255,255,.18),inset -6px -6px rgba(57,117,121,.17); }
.lc-held-voxel[data-block="tnt"] .lc-held-voxel__face:not(.lc-held-voxel__face--top) { background-image: linear-gradient(0deg,transparent 0 32%,#efe1bb 32% 66%,transparent 66%),repeating-linear-gradient(90deg,transparent 0 14px,var(--lc-voxel-dark) 14px 18px); }.lc-held-voxel[data-block="tnt"] .lc-held-voxel__face--top { background-image: radial-gradient(circle at 50% 50%,#24211d 0 9%,transparent 10%),repeating-conic-gradient(var(--lc-voxel-accent) 0 12deg,var(--lc-voxel-dark) 13deg 24deg); }.lc-held-voxel[data-block="tnt"] .lc-held-voxel__face::after { content:none; }
@keyframes lc-held-item-swing { 0%,100% { transform: translate3d(0,0,0) rotateZ(-2deg) rotateX(0); } 45% { transform: translate3d(-35%,18%,0) rotateZ(-38deg) rotateX(12deg) scale(.92); } }
.lc-survival-wrap { bottom: max(6px, env(safe-area-inset-bottom)); left: 50%; pointer-events: auto; position: absolute; transform: translateX(-50%); width: 364px; z-index: 2; }
.lc-survival { display: grid; grid-template-columns: 1fr 1fr; height: 39px; margin: 0 2px 2px; }
.lc-meter { align-items: center; display: flex; height: 18px; }
.lc-meter--health, .lc-meter--armor { justify-content: flex-start; }.lc-meter--hunger { flex-direction: row-reverse; justify-content: flex-start; }
.lc-meter__icon { display: block; filter: drop-shadow(1px 1px 0 #161616); flex: 0 0 18px; height: 18px; width: 18px; }
.lc-meter__icon > svg { display: block; height: 18px; image-rendering: pixelated; overflow: visible; width: 18px; }
.lc-meter__outline { fill: var(--meter-outline); }.lc-meter__empty { fill: var(--meter-empty); }.lc-meter__fill { fill: var(--meter-fill); }.lc-meter__highlight { fill: var(--meter-highlight); }
.lc-meter__fill-layer { overflow: hidden; }
.lc-meter--health { --meter-outline: #260808; --meter-empty: #501a18; --meter-fill: #d83c35; --meter-highlight: #ff7669; }
.lc-meter--hunger { --meter-outline: #241208; --meter-empty: #50301c; --meter-fill: #b8672b; --meter-highlight: #e8a254; }
.lc-meter--armor { --meter-outline: #1d2428; --meter-empty: #465158; --meter-fill: #bbcbd1; --meter-highlight: #f2fbff; }
.lc-selected-item-name { bottom: calc(100% + 2px); color: #fff; font: 16px/1.2 var(--lc-pixel-font); left: 50%; max-width: min(330px,calc(100vw - 20px)); pointer-events: none; position: absolute; text-align: center; text-shadow: 2px 2px #202020; transform: translateX(-50%); width: 100%; }
.lc-selected-item-name > span { animation: lc-selected-item-name 2s linear both; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
@keyframes lc-selected-item-name { 0%,70% { opacity: 1; } 100% { opacity: 0; } }
.lc-hotbar { background: rgba(18,18,18,.62); border: 2px solid #191919; box-shadow: inset 2px 2px rgba(255,255,255,.2),inset -2px -2px rgba(0,0,0,.72),2px 2px 0 rgba(0,0,0,.6); box-sizing: border-box; display: grid; gap: 0; grid-template-columns: repeat(9, 40px); overflow: visible; padding: 0; position: relative; width: 100%; }
.lc-slot { appearance: none; background: rgba(28,28,28,.66); border: 2px solid; border-color: #373737 #b8b8b8 #b8b8b8 #373737; color: var(--lc-paper); cursor: pointer; min-width: 0; padding: 0; position: relative; }
.lc-slot:hover { background: rgba(70,70,70,.7); }
.lc-slot:focus-visible, .lc-recipe:focus-visible, .lc-close:focus-visible, .lc-furnace-slot:focus-visible, .lc-furnace-inventory-slot:focus-visible, .lc-furnace__header button:focus-visible { outline: 2px solid var(--lc-amber); outline-offset: 2px; }
.lc-hotbar__slot { box-sizing: border-box; height: 40px; }.lc-hotbar__slot.is-selected { background: rgba(90,90,90,.64); border-color: #777; box-shadow: none; z-index: 2; }.lc-hotbar__slot.is-selected::after { border: 2px solid #fff; box-shadow: inset 0 0 0 2px #777,0 0 0 1px #333; box-sizing: border-box; content: ""; height: 48px; left: 50%; pointer-events: none; position: absolute; top: 50%; transform: translate(-50%,-50%); width: 48px; }
.lc-item-glyph { align-items: center; display: flex; height: 100%; justify-content: center; min-height: 34px; overflow: hidden; position: relative; width: 100%; }
.lc-item-icon__svg { display: block; filter: drop-shadow(1px 2px 0 rgba(0,0,0,.42)); height: min(34px,calc(100% - 4px)); image-rendering: pixelated; overflow: visible; width: min(34px,calc(100% - 4px)); }
.lc-item-glyph--block .lc-item-icon__svg { height: min(36px,calc(100% - 3px)); width: min(36px,calc(100% - 3px)); }
.lc-item-glyph__count { background: none; bottom: 2px; color: #fff; font: 900 13px/1 var(--lc-pixel-font); min-width: 11px; padding: 0; position: absolute; right: 2px; text-align: right; text-shadow: 2px 2px #303030; z-index: 2; }
.lc-durability { background: #171717; bottom: 2px; display: block; height: 4px; left: 4px; padding: 1px; position: absolute; right: 4px; z-index: 3; }.lc-durability > span { display: block; height: 2px; image-rendering: pixelated; }
.lc-item-glyph.is-muted { filter: grayscale(1); opacity: .45; }
.lc-player-list { background: rgba(0,0,0,.55); color: #fff; left: 50%; max-width: min(620px, calc(100vw - 24px)); min-width: 330px; padding: 8px 10px 10px; pointer-events: none; position: absolute; text-shadow: 2px 2px #202020; top: 18px; transform: translateX(-50%); }
.lc-player-list h2 { font: 16px/1.2 var(--lc-pixel-font); margin: 0 0 7px; text-align: center; }.lc-player-list ul { display: grid; gap: 2px 18px; grid-template-columns: repeat(auto-fit,minmax(145px,1fr)); list-style: none; margin: 0; padding: 0; }.lc-player-list li { align-items: center; display: grid; font: 14px/18px var(--lc-pixel-font); grid-template-columns: 18px 1fr 20px; min-width: 0; }.lc-player-list li > span:nth-child(2) { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.lc-player-list__head { background: linear-gradient(#9a6642 0 28%,#c98e6d 28% 78%,#68442e 78%); box-shadow: inset 0 0 0 1px rgba(0,0,0,.35); height: 16px; width: 16px; }.lc-player-list__signal { align-items: end; display: flex; gap: 1px; height: 13px; justify-content: flex-end; }.lc-player-list__signal i { background: #555; display: block; height: 3px; width: 2px; }.lc-player-list__signal i:nth-child(2) { height: 5px; }.lc-player-list__signal i:nth-child(3) { height: 7px; }.lc-player-list__signal i:nth-child(4) { height: 9px; }.lc-player-list__signal i:nth-child(5) { height: 11px; }.lc-player-list__signal i.is-on { background: #62c558; box-shadow: 1px 0 #183e15; }
.lc-menu-layer { align-items: flex-start; background: rgba(0,0,0,.55); display: flex; inset: 0; justify-content: center; overflow-y: auto; padding: clamp(58px, 13vh, 126px) 14px 24px; position: fixed; z-index: 80; }
.lc-game-menu { color: #fff; max-width: min(400px, calc(100vw - 28px)); text-align: center; text-shadow: 2px 2px #202020; width: 100%; }.lc-game-menu h2 { font: 20px/1.2 var(--lc-pixel-font); font-weight: 400; margin: 0 0 clamp(34px,8vh,74px); }.lc-game-menu__buttons { display: grid; gap: 8px; }.lc-game-menu button { background: #777; border: 2px solid #111; box-shadow: inset 2px 2px #aaa, inset -2px -2px #555; color: #fff; cursor: pointer; font: 16px/1 var(--lc-pixel-font); min-height: 40px; padding: 8px 18px; text-shadow: 2px 2px #333; }.lc-game-menu button:hover:not(:disabled), .lc-game-menu button:focus-visible { background: #6b6bb6; box-shadow: inset 2px 2px #9b9be1, inset -2px -2px #3c3c76; outline: 2px solid #fff; }.lc-game-menu button:disabled { color: #aaa; cursor: default; }.lc-game-menu__save { display: grid; gap: 5px; }.lc-game-menu__save-status { color: #ddd; display: grid; font: 12px/1.35 var(--lc-pixel-font); min-height: 16px; padding: 0 8px; text-shadow: 1px 1px #202020; }.lc-game-menu__last-saved { color: #aaa; }.lc-game-menu__disconnect { margin-top: 12px; }
.lc-death-layer { align-items: flex-start; background: rgba(128,0,0,.58); display: flex; inset: 0; justify-content: center; padding: clamp(56px,15vh,136px) 14px 24px; position: fixed; z-index: 90; }
.lc-death-screen { color: #fff; max-width: 400px; text-align: center; text-shadow: 3px 3px #3f0000; width: 100%; }.lc-death-screen h2 { font: 40px/1.1 var(--lc-pixel-font); font-weight: 400; margin: 0 0 20px; }.lc-death-screen__cause { font: 16px/1.35 var(--lc-pixel-font); margin: 0 0 12px; min-height: 1.35em; }.lc-death-screen__score { font: 16px/1.25 var(--lc-pixel-font); margin: 0 0 clamp(34px,8vh,76px); }.lc-death-screen__score strong { color: #ffff55; font-weight: 400; }.lc-death-screen__buttons { display: grid; gap: 8px; }.lc-death-screen button { background: #777; border: 2px solid #111; box-shadow: inset 2px 2px #aaa,inset -2px -2px #555; color: #fff; cursor: pointer; font: 16px/1 var(--lc-pixel-font); min-height: 40px; padding: 8px 18px; text-shadow: 2px 2px #333; }.lc-death-screen button:hover:not(:disabled),.lc-death-screen button:focus-visible { background: #6b6bb6; box-shadow: inset 2px 2px #9b9be1,inset -2px -2px #3c3c76; outline: 2px solid #fff; }.lc-death-screen button:disabled { color: #aaa; cursor: default; }.lc-death-screen__status { background: rgba(48,0,0,.78); border: 2px solid #3f0000; color: #fff; font: 12px/1.35 var(--lc-pixel-font); margin: 10px 0 0; padding: 6px 8px; text-align: left; text-shadow: 2px 2px #200; }.lc-death-screen__status.is-error { border-color: #ff5555; color: #ffaaaa; }
.lc-toasts { display: flex; flex-direction: column; gap: 4px; pointer-events: auto; position: absolute; right: 12px; top: 12px; width: min(300px,calc(100vw - 24px)); }
.lc-toast { --lc-toast-edge: #55a7d8; animation: lc-toast-in .15s steps(3,end) both; appearance: none; background: rgba(16,16,16,.88); border: 2px solid #050505; border-left: 5px solid var(--lc-toast-edge); color: #fff; cursor: pointer; display: block; padding: 7px 10px 8px; text-align: left; text-shadow: 2px 2px #202020; }
.lc-toast--success { --lc-toast-edge: #55c653; }.lc-toast--warning { --lc-toast-edge: #f5c542; }
.lc-toast strong { display: block; font-size: 12px; line-height: 1.2; }.lc-toast small { color: #fff; display: block; font: 10px/1.35 var(--lc-note); margin-top: 2px; }
@keyframes lc-toast-in { from { opacity: 0; transform: translateX(18px); } }
.lc-drawer-layer { align-items: center; background: rgba(8,10,8,.67); backdrop-filter: blur(4px); display: flex; inset: 0; justify-content: center; padding: 28px; position: fixed; z-index: 60; }
.lc-drawer { background-color: #d9cfb3; background-image: linear-gradient(rgba(74,81,59,.075) 1px, transparent 1px), linear-gradient(90deg, rgba(74,81,59,.045) 1px, transparent 1px); background-size: 100% 24px, 24px 100%; border: 1px solid #eee5ce; box-shadow: 0 24px 80px rgba(0,0,0,.55), inset 0 0 0 5px rgba(87,77,49,.13); color: var(--lc-ink); max-height: calc(100vh - 56px); max-height: calc(100dvh - 56px); max-width: 1040px; overflow: auto; position: relative; width: 100%; }
.lc-drawer::before { background: var(--lc-moss); content: ""; height: 7px; left: 0; position: absolute; right: 0; top: 0; }
.lc-drawer__heading { align-items: flex-end; border-bottom: 2px solid rgba(36,38,31,.7); display: flex; justify-content: space-between; margin: 30px 32px 0; padding-bottom: 14px; }.lc-drawer__heading h2 { font-size: clamp(24px, 4vw, 38px); letter-spacing: -.04em; line-height: 1; margin: 5px 0 0; text-transform: uppercase; }.lc-drawer__heading .lc-kicker { color: var(--lc-rust); }
.lc-close { align-items: center; background: none; border: 0; color: var(--lc-ink); cursor: pointer; display: flex; gap: 9px; padding: 5px; }.lc-close span { font: 9px var(--lc-note); letter-spacing: .1em; text-transform: uppercase; }.lc-close kbd { border: 1px solid rgba(36,38,31,.45); box-shadow: 0 2px rgba(36,38,31,.3); font: 10px var(--lc-note); padding: 5px 8px; }
.lc-drawer__body { display: grid; gap: 32px; grid-template-columns: minmax(330px, 1fr) minmax(330px, 1.1fr); padding: 25px 32px 33px; }
.lc-section-rule { align-items: baseline; border-bottom: 1px solid rgba(36,38,31,.28); display: flex; justify-content: space-between; margin-bottom: 13px; padding-bottom: 7px; }.lc-section-rule h3 { font-size: 12px; letter-spacing: .12em; margin: 0; text-transform: uppercase; }.lc-section-rule small { color: rgba(36,38,31,.56); font: 9px var(--lc-note); }
.lc-inventory-grid { background: rgba(36,38,31,.87); border: 4px solid rgba(36,38,31,.18); display: grid; gap: 3px; grid-template-columns: repeat(9, 1fr); padding: 5px; }
.lc-inventory-grid__slot { aspect-ratio: 1; min-width: 0; }.lc-inventory-grid__slot:nth-child(-n+9) { border-bottom-color: var(--lc-amber); }.lc-inventory-grid__slot.is-selected { background: rgba(212,154,69,.18); border-color: var(--lc-amber); }
.lc-inventory-grid .lc-item-icon__svg { height: min(38px,calc(100% - 5px)); width: min(38px,calc(100% - 5px)); }.lc-pencil-note { color: rgba(36,38,31,.64); font: italic 10px/1.5 var(--lc-note); margin: 12px 4px 0; transform: rotate(-.4deg); }
.lc-armor-rack { align-items: stretch; background: rgba(36,38,31,.08); border: 1px solid rgba(36,38,31,.18); display: grid; gap: 5px; grid-template-columns: 1fr repeat(4, 48px); margin-top: 12px; padding: 7px; }.lc-armor-rack > div { align-self: center; padding-left: 5px; }.lc-armor-rack > div strong { display: block; font-size: 10px; letter-spacing: .08em; text-transform: uppercase; }.lc-armor-rack > div small { color: rgba(36,38,31,.56); font: 8px var(--lc-note); }.lc-armor-slot { background: rgba(36,38,31,.84); border: 1px solid rgba(36,38,31,.2); color: var(--lc-paper); cursor: pointer; height: 48px; padding: 0; position: relative; }.lc-armor-slot:disabled { cursor: default; opacity: .35; }.lc-armor-slot > span { color: rgba(230,220,193,.45); font: 6px var(--lc-note); left: 3px; position: absolute; text-transform: uppercase; top: 2px; z-index: 2; }.lc-armor-slot .lc-item-glyph { min-height: 46px; }.lc-armor-slot .lc-item-icon__svg { height: 36px; width: 36px; }
.lc-recipe-list { display: flex; flex-direction: column; gap: 6px; }.lc-recipe { align-items: center; appearance: none; background: rgba(255,255,255,.16); border: 1px solid rgba(36,38,31,.17); color: var(--lc-ink); cursor: pointer; display: grid; gap: 10px; grid-template-columns: 26px 1fr auto 46px; min-height: 59px; padding: 8px 9px; text-align: left; transition: background .15s, transform .15s; }.lc-recipe:not(:disabled):hover { background: rgba(255,255,255,.42); transform: translateX(-3px); }.lc-recipe:disabled { cursor: not-allowed; filter: saturate(.4); opacity: .55; }.lc-recipe.is-ready { border-left: 3px solid var(--lc-moss); }
.lc-recipe__number { color: rgba(36,38,31,.46); font: 8px var(--lc-note); }.lc-recipe__output { align-items: center; display: flex; gap: 9px; min-width: 0; }.lc-recipe__output > b { align-items: center; display: flex; height: 34px; justify-content: center; width: 34px; }.lc-recipe__output strong { display: block; font-size: 11px; letter-spacing: .03em; }.lc-recipe__output small { color: rgba(36,38,31,.56); display: block; font: 8px/1.3 var(--lc-note); margin-top: 2px; }.lc-recipe__ingredients { align-items: center; display: flex; gap: 4px; }.lc-ingredient { align-items: center; background: rgba(36,38,31,.08); display: flex; font: 9px var(--lc-note); gap: 2px; padding: 3px 4px; }.lc-ingredient.is-short { color: var(--lc-rust); text-decoration: line-through; }.lc-ingredient__icon { display: block; height: 18px; width: 18px; }.lc-ingredient__icon .lc-item-glyph { min-height: 18px; }.lc-ingredient__icon .lc-item-icon__svg { filter: drop-shadow(1px 1px 0 rgba(0,0,0,.3)); height: 18px; width: 18px; }.lc-recipe__arrow { color: rgba(36,38,31,.4); }.lc-recipe__action { border: 1px solid rgba(36,38,31,.35); font: 8px var(--lc-note); letter-spacing: .08em; padding: 6px 4px; text-align: center; }.lc-recipe.is-ready .lc-recipe__action { background: var(--lc-moss); border-color: var(--lc-moss); color: #f1e8ce; }
.lc-drawer-layer { backdrop-filter: none; background: rgba(0,0,0,.55); padding: 14px; }
.lc-inventory-window { background: #c6c6c6; background-image: none; border: 4px solid #111; border-radius: 0; box-shadow: inset 4px 4px #fff, inset -4px -4px #555, 0 18px 56px rgba(0,0,0,.6); color: #3f3f3f; max-height: calc(100dvh - 28px); max-width: 704px; overflow: auto; padding: 20px 24px 18px; width: auto; }
.lc-inventory-window::before { content: none; }
.lc-inventory-titlebar { align-items: center; display: flex; justify-content: space-between; margin-bottom: 13px; }.lc-inventory-titlebar h2 { color: #3f3f3f; font: 18px/1 var(--lc-pixel-font); font-weight: 400; margin: 0; text-shadow: 1px 1px #fff; }.lc-inventory-titlebar .lc-close { color: #3f3f3f; padding: 0; }.lc-inventory-titlebar .lc-close span { font-size: 10px; }.lc-inventory-titlebar .lc-close kbd { background: #8b8b8b; border: 2px solid; border-color: #fff #373737 #373737 #fff; color: #fff; text-shadow: 1px 1px #333; }
.lc-inventory-upper { align-items: stretch; display: grid; gap: 34px; grid-template-columns: 254px 1fr; min-height: 190px; }
.lc-equipment-panel { display: grid; gap: 8px; grid-template-columns: 48px 1fr; position: relative; }.lc-armor-column { display: grid; gap: 0; grid-template-rows: repeat(4,48px); }.lc-inventory-window .lc-armor-slot { background: #8b8b8b; border: 2px solid; border-color: #373737 #fff #fff #373737; height: 48px; opacity: 1; width: 48px; }.lc-inventory-window .lc-armor-slot:disabled { opacity: .48; }.lc-armor-slot__label { color: rgba(255,255,255,.55); font: 9px/1 var(--lc-pixel-font); left: 4px; position: absolute; top: 4px; z-index: 3; }
.lc-player-preview { background: #262626; border: 2px solid; border-color: #373737 #fff #fff #373737; min-height: 192px; overflow: hidden; perspective: 360px; position: relative; }.lc-player-preview > span { display: block; position: absolute; transform: rotateY(-18deg); transform-style: preserve-3d; }.lc-player-preview > span::after { background: var(--preview-side); content: ""; height: 100%; position: absolute; right: -6px; top: 0; transform: rotateY(90deg); transform-origin: left; width: 6px; }.lc-player-preview__head { --preview-side: linear-gradient(#3b2319 0 22%,#754531 22%); background: linear-gradient(#4b2d1c 0 22%,transparent 22%),linear-gradient(90deg,transparent 18%,#45658a 18% 28%,transparent 28% 72%,#45658a 72% 82%,transparent 82%) 0 21px/100% 4px no-repeat,#b97855; height: 40px; left: calc(50% - 20px); top: 12px; width: 40px; }.lc-player-preview__head::before { background: #4b2d1c; content: ""; height: 6px; left: 0; position: absolute; top: -6px; transform: rotateX(90deg); transform-origin: bottom; width: 100%; }.lc-player-preview__body { --preview-side: #155b67; background: linear-gradient(90deg,#39a3a1 0 78%,#287f87 78%); height: 60px; left: calc(50% - 20px); top: 52px; width: 40px; }.lc-player-preview__arm { --preview-side: linear-gradient(#125963 0 28%,#754531 28%); background: linear-gradient(#24969b 0 28%,#b97855 28%); height: 60px; top: 52px; width: 20px; }.lc-player-preview__arm--left { left: calc(50% - 40px); }.lc-player-preview__arm--right { left: calc(50% + 20px); }.lc-player-preview__leg { --preview-side: #1d2d62; background: #334d9b; height: 60px; top: 112px; width: 20px; }.lc-player-preview__leg--left { left: calc(50% - 20px); }.lc-player-preview__leg--right { left: 50%; }
.lc-inventory-window .lc-crafting-panel { align-self: center; min-width: 0; }.lc-inventory-window h3 { color: #3f3f3f; font: 14px/1 var(--lc-pixel-font); font-weight: 400; margin: 0 0 8px; text-shadow: 1px 1px #fff; }.lc-inventory-window.is-crafting-table .lc-inventory-upper { display: block; min-height: 0; }.lc-inventory-window.is-crafting-table .lc-crafting-panel { margin: 0 auto; width: max-content; }
.lc-crafting-workspace { align-items: center; display: flex; gap: 16px; }.lc-crafting-grid { display: grid; grid-template-columns: repeat(var(--craft-grid-size),48px); }.lc-crafting-slot,.lc-crafting-result { background: #8b8b8b; border: 2px solid; border-color: #373737 #fff #fff #373737; height: 48px; width: 48px; }.lc-crafting-slot:hover,.lc-crafting-result:not(:disabled):hover { background: #a5a5a5; }.lc-crafting-result:disabled { cursor: default; }.lc-crafting-result.is-ready { box-shadow: 0 0 0 2px rgba(255,255,255,.3); }.lc-crafting-arrow { color: #6a6a6a; font: 34px/1 Arial,sans-serif; text-shadow: 1px 1px #fff; }
.lc-pack-panel { margin-top: 15px; }.lc-inventory-window .lc-inventory-grid { background: transparent; border: 0; display: grid; gap: 0; grid-template-columns: repeat(9,48px); padding: 0; width: 432px; }.lc-inventory-window .lc-inventory-grid__slot { aspect-ratio: auto; background: #8b8b8b; border: 2px solid; border-color: #373737 #fff #fff #373737; height: 48px; width: 48px; }.lc-inventory-window .lc-inventory-grid__slot:nth-child(-n+9) { border-bottom-color: #fff; }.lc-inventory-window .lc-inventory-grid__slot.is-selected { background: #9f9f9f; border-color: #373737 #fff #fff #373737; box-shadow: inset 0 0 0 2px rgba(255,255,255,.75); }.lc-inventory-window .lc-inventory-grid__slot.is-hotbar { margin-top: 12px; }.lc-inventory-window .lc-item-icon__svg { height: min(40px,calc(100% - 5px)); width: min(40px,calc(100% - 5px)); }
.lc-cursor-stack { background: #8b8b8b; border: 2px solid rgba(255,255,255,.7); color: #fff; height: 44px; pointer-events: none; position: fixed; width: 44px; z-index: 90; }.lc-cursor-stack .lc-item-glyph { min-height: 44px; }
.lc-furnace-layer { align-items: center; background: rgba(0,0,0,.56); display: flex; font-family: var(--lc-pixel-font); image-rendering: pixelated; inset: 0; justify-content: center; padding: 20px; position: fixed; z-index: 65; }
.lc-furnace { --lc-furnace-slot: 48px; background: #c6c6c6; border: 4px solid #111; box-shadow: inset 4px 4px #fff,inset -4px -4px #555,0 18px 56px rgba(0,0,0,.66); color: #3f3f3f; max-height: calc(100vh - 40px); max-height: calc(100dvh - 40px); overflow: auto; padding: 18px 22px 16px; width: 500px; }
.lc-furnace__header { align-items: center; display: flex; justify-content: space-between; margin-bottom: 12px; }.lc-furnace__header h2,.lc-furnace__inventory h3 { color: #3f3f3f; font: 16px/1 var(--lc-pixel-font); font-weight: 400; margin: 0; text-shadow: 1px 1px #fff; }.lc-furnace__header button { align-items: center; background: none; border: 0; color: #3f3f3f; cursor: pointer; display: flex; font: 10px/1 var(--lc-pixel-font); gap: 7px; padding: 0; }.lc-furnace__header button:disabled { cursor: wait; opacity: .45; }.lc-furnace__header kbd { background: #8b8b8b; border: 2px solid; border-color: #fff #373737 #373737 #fff; color: #fff; font: 10px/1 var(--lc-pixel-font); padding: 4px 6px; text-shadow: 1px 1px #333; }
.lc-furnace__station { align-items: center; display: grid; grid-template-columns: var(--lc-furnace-slot) 72px var(--lc-furnace-slot); justify-content: center; min-height: 157px; padding: 3px 0 17px; }.lc-furnace__source { align-items: center; display: flex; flex-direction: column; gap: 5px; }.lc-furnace-slot,.lc-furnace-inventory-slot { appearance: none; background: #8b8b8b; border: 2px solid; border-color: #373737 #fff #fff #373737; color: #fff; cursor: pointer; height: var(--lc-furnace-slot); min-width: 0; padding: 0; position: relative; width: var(--lc-furnace-slot); }.lc-furnace-slot:hover:not(:disabled),.lc-furnace-inventory-slot.is-eligible:hover:not(:disabled) { background: #a5a5a5; }.lc-furnace-slot:disabled,.lc-furnace-inventory-slot:disabled { cursor: default; }.lc-furnace-slot .lc-item-glyph,.lc-furnace-inventory-slot .lc-item-glyph { min-height: calc(var(--lc-furnace-slot) - 4px); }.lc-furnace-slot .lc-item-icon__svg,.lc-furnace-inventory-slot .lc-item-icon__svg { height: min(40px,calc(100% - 4px)); width: min(40px,calc(100% - 4px)); }
.lc-furnace__flame { background: #6f6f6f; clip-path: polygon(42% 0,63% 28%,76% 17%,89% 53%,82% 82%,66% 100%,33% 100%,14% 75%,17% 43%); display: block; height: 23px; overflow: hidden; position: relative; width: 19px; }.lc-furnace__flame i { background: #f5a623; bottom: 0; box-shadow: inset 0 4px #ffde55; display: block; left: 0; position: absolute; width: 100%; }.lc-furnace__arrow { background: #777; clip-path: polygon(0 27%,68% 27%,68% 0,100% 50%,68% 100%,68% 73%,0 73%); display: block; height: 26px; margin: 0 auto; overflow: hidden; position: relative; width: 54px; }.lc-furnace__arrow i { background: #fff; display: block; height: 100%; left: 0; position: absolute; top: 0; }
.lc-furnace__inventory h3 { font-size: 13px; margin-bottom: 7px; }.lc-furnace-inventory-grid { display: grid; grid-template-columns: repeat(9,var(--lc-furnace-slot)); justify-content: center; }.lc-furnace-inventory-grid--hotbar { margin-top: 11px; }.lc-furnace-inventory-slot:not(.is-eligible) { filter: none; opacity: 1; }.lc-furnace-inventory-slot:not(.is-eligible):disabled .lc-item-glyph { opacity: .72; }.lc-furnace-inventory-slot.is-eligible { box-shadow: inset 0 0 0 1px rgba(255,255,255,.22); }.lc-furnace__status { color: #555; font: 9px/1.4 var(--lc-pixel-font); margin: 13px 0 0; min-height: 1.4em; text-shadow: 1px 1px #fff; }.lc-furnace__status.is-error { color: #a40000; }
.lc-unsupported { align-items: center; background: var(--lc-charcoal); display: flex; inset: 0; justify-content: center; overflow: hidden; padding: 24px; position: fixed; z-index: 100; }.lc-unsupported__topo { background: repeating-radial-gradient(ellipse at 80% 20%, transparent 0 26px, rgba(168,182,107,.08) 27px 28px, transparent 29px 42px); inset: -30%; position: absolute; transform: rotate(-10deg); }.lc-unsupported__card { background: var(--lc-paper); box-shadow: 12px 14px 0 rgba(102,117,65,.48); color: var(--lc-ink); max-width: 390px; padding: 34px 31px; position: relative; transform: rotate(-1deg); }.lc-unsupported__stamp { border: 1px solid var(--lc-rust); color: var(--lc-rust); font: 9px var(--lc-note); letter-spacing: .12em; padding: 5px 7px; }.lc-unsupported__icon { color: var(--lc-moss); font: 900 44px/1 var(--lc-display); margin-top: 27px; }.lc-unsupported h2 { font-size: 35px; letter-spacing: -.045em; line-height: .95; margin: 13px 0 16px; text-transform: uppercase; }.lc-unsupported p { font: 13px/1.6 var(--lc-note); }.lc-unsupported button { align-items: center; background: var(--lc-ink); border: 0; color: var(--lc-paper); cursor: pointer; display: flex; justify-content: space-between; margin-top: 22px; padding: 13px 16px; width: 100%; }.lc-unsupported small { color: rgba(36,38,31,.55); display: block; font: 9px var(--lc-note); margin-top: 13px; }
@media (max-width: 820px) { .lc-survival-wrap { max-width: calc(100vw - 12px); }.lc-hotbar { grid-template-columns: repeat(9, minmax(0, 1fr)); }.lc-hotbar__slot { height: min(40px, calc((100vw - 20px) / 9)); }.lc-player-list { min-width: min(330px,calc(100vw - 24px)); }.lc-drawer-layer,.lc-furnace-layer { padding: 10px; }.lc-drawer,.lc-furnace { max-height: calc(100vh - 20px); max-height: calc(100dvh - 20px); }.lc-drawer__body { grid-template-columns: 1fr; }.lc-inventory-grid { grid-template-columns: repeat(9, 1fr); }.lc-drawer__heading { margin-inline: 19px; }.lc-drawer__body { padding: 20px 19px 25px; }.lc-inventory-window { max-width: calc(100vw - 20px); padding: 17px; }.lc-inventory-upper { gap: 18px; grid-template-columns: 220px 1fr; }.lc-inventory-window .lc-inventory-grid { grid-template-columns: repeat(9,minmax(0,48px)); max-width: 432px; width: 100%; }.lc-inventory-window .lc-inventory-grid__slot { width: 100%; } }
@media (max-width: 560px) { .lc-recipe { grid-template-columns: 22px 1fr 42px; }.lc-recipe__ingredients { grid-column: 2 / 4; }.lc-inventory-upper { grid-template-columns: 1fr; }.lc-equipment-panel { display: none; }.lc-inventory-window .lc-inventory-grid { grid-template-columns: repeat(9,minmax(0,1fr)); }.lc-inventory-window .lc-inventory-grid__slot { height: min(48px,calc((100vw - 62px)/9)); }.lc-crafting-workspace { justify-content: center; }.lc-furnace { --lc-furnace-slot: calc((100vw - 66px)/9); padding: 15px 17px 14px; width: 100%; }.lc-furnace__station { grid-template-columns: var(--lc-furnace-slot) 58px var(--lc-furnace-slot); min-height: 137px; }.lc-furnace__arrow { width: 44px; } }
@media (prefers-reduced-motion: reduce) { .lc-toast,.lc-first-person__rig.is-swinging { animation: none; }.lc-slot,.lc-recipe { transition: none; } }
`;

export function HudStyles() {
  return <style>{HUD_CSS}</style>;
}
