const HUD_CSS = `
:root {
  --lc-paper: #e6dcc1;
  --lc-paper-deep: #c9b98f;
  --lc-ink: #24261f;
  --lc-charcoal: #171a16;
  --lc-moss: #667541;
  --lc-moss-bright: #a8b66b;
  --lc-amber: #d49a45;
  --lc-rust: #9a5434;
  --lc-line: rgba(33, 37, 29, .2);
  --lc-shadow: rgba(10, 12, 9, .45);
  --lc-pixel-font: "Pixelify Sans", "Courier New", Courier, monospace;
  --lc-display: var(--lc-pixel-font);
  --lc-note: var(--lc-pixel-font);
}
.lc-hud, .lc-drawer-layer, .lc-unsupported, .lc-menu-layer { color: var(--lc-paper); font-family: var(--lc-pixel-font); image-rendering: pixelated; }
.lc-hud { height: 100vh; height: 100dvh; inset: 0 auto auto 0; overflow: hidden; pointer-events: none; position: fixed; width: 100vw; z-index: 20; }
.lc-hud button, .lc-drawer-layer button, .lc-unsupported button, .lc-menu-layer button { font: inherit; }
.lc-kicker { color: var(--lc-amber); font: 9px/1.2 var(--lc-note); letter-spacing: .14em; text-transform: uppercase; }
.lc-crosshair { filter: drop-shadow(1px 1px 0 #000) drop-shadow(-1px -1px 0 rgba(0,0,0,.65)); height: 16px; left: 50%; position: absolute; top: 50%; transform: translate(-50%, -50%); width: 16px; }
.lc-crosshair::before, .lc-crosshair::after { background: rgba(255,255,255,.94); content: ""; left: 50%; position: absolute; top: 50%; transform: translate(-50%,-50%); }
.lc-crosshair::before { height: 2px; width: 16px; }.lc-crosshair::after { height: 16px; width: 2px; }
.lc-survival-wrap { bottom: max(6px, env(safe-area-inset-bottom)); left: 50%; pointer-events: auto; position: absolute; transform: translateX(-50%); width: 364px; }
.lc-survival { display: grid; grid-template-columns: 1fr 1fr; height: 39px; margin: 0 2px 2px; }
.lc-meter { align-items: center; display: flex; height: 18px; }
.lc-meter--health, .lc-meter--armor { justify-content: flex-start; }.lc-meter--hunger { justify-content: flex-end; }
.lc-meter__icon { --meter-fill: 0%; background: linear-gradient(90deg, var(--meter-color) var(--meter-fill), rgba(20,20,20,.7) var(--meter-fill)); background-clip: text; color: transparent; filter: drop-shadow(1px 1px 0 #161616); font: 18px/18px Arial, sans-serif; height: 18px; position: relative; text-align: center; width: 18px; -webkit-background-clip: text; }
.lc-meter__icon[data-state="full"] { --meter-fill: 100%; }.lc-meter__icon[data-state="half"] { --meter-fill: 50%; }
.lc-meter__icon::before { content: "♥"; }.lc-meter--health { --meter-color: #d83333; }
.lc-meter--hunger { --meter-color: #b86b31; }.lc-meter--hunger .lc-meter__icon::before { content: "●"; font-size: 16px; }.lc-meter--hunger .lc-meter__icon::after { background: currentColor; box-shadow: 1px 1px 0 #161616; content: ""; height: 7px; position: absolute; right: 1px; top: 1px; transform: rotate(45deg); width: 3px; }
.lc-meter--armor { --meter-color: #d6d6d6; }.lc-meter--armor .lc-meter__icon::before { content: "♢"; font-size: 20px; font-weight: 900; }
.lc-hotbar { background: #8b8b8b; border: 2px solid #191919; box-shadow: inset 2px 2px #d0d0d0, inset -2px -2px #373737, 2px 2px 0 rgba(0,0,0,.6); display: grid; gap: 0; grid-template-columns: repeat(9, 40px); padding: 2px; position: relative; }
.lc-slot { appearance: none; background: rgba(28,28,28,.66); border: 2px solid; border-color: #373737 #b8b8b8 #b8b8b8 #373737; color: var(--lc-paper); cursor: pointer; min-width: 0; padding: 0; position: relative; }
.lc-slot:hover { background: rgba(70,70,70,.7); }
.lc-slot:focus-visible, .lc-recipe:focus-visible, .lc-close:focus-visible, .lc-furnace-recipe:focus-visible, .lc-furnace__header button:focus-visible { outline: 2px solid var(--lc-amber); outline-offset: 2px; }
.lc-hotbar__slot { height: 40px; }.lc-hotbar__slot.is-selected { background: rgba(90,90,90,.64); box-shadow: inset 0 0 0 2px #fff, inset 0 0 0 4px #777; border-color: #fff; z-index: 1; }
.lc-slot__key, .lc-slot__index { color: rgba(230,220,193,.44); font: 8px var(--lc-note); left: 4px; position: absolute; top: 3px; z-index: 2; }
.lc-item-glyph { align-items: center; display: flex; height: 100%; justify-content: center; min-height: 34px; overflow: hidden; position: relative; width: 100%; }
.lc-item-glyph::before { background: color-mix(in srgb, var(--item-color), transparent 78%); border: 1px solid color-mix(in srgb, var(--item-color), white 16%); box-shadow: inset 3px 3px rgba(255,255,255,.06), inset -4px -4px rgba(0,0,0,.14); content: ""; height: 25px; position: absolute; transform: rotate(-2deg); width: 25px; }
.lc-item-glyph--tool::before, .lc-item-glyph--material::before { border-radius: 50%; transform: rotate(0); }
.lc-item-glyph--empty::before { background: none; border: 1px dashed rgba(230,220,193,.07); box-shadow: none; }
.lc-item-glyph__mark { color: var(--item-color); filter: drop-shadow(1px 2px 0 rgba(0,0,0,.4)); font: 900 22px/1 Georgia, serif; position: relative; z-index: 1; }
.lc-item-glyph__code { bottom: 3px; color: rgba(230,220,193,.68); font: 7px var(--lc-note); left: 4px; letter-spacing: .06em; position: absolute; }
.lc-item-glyph__count { background: none; bottom: 2px; color: #fff; font: 900 13px/1 var(--lc-pixel-font); min-width: 11px; padding: 0; position: absolute; right: 2px; text-align: right; text-shadow: 2px 2px #303030; z-index: 2; }
.lc-item-glyph.is-muted { filter: grayscale(1); opacity: .45; }
.lc-player-list { background: rgba(0,0,0,.55); color: #fff; left: 50%; max-width: min(620px, calc(100vw - 24px)); min-width: 330px; padding: 8px 10px 10px; pointer-events: none; position: absolute; text-shadow: 2px 2px #202020; top: 18px; transform: translateX(-50%); }
.lc-player-list h2 { font: 16px/1.2 var(--lc-pixel-font); margin: 0 0 7px; text-align: center; }.lc-player-list ul { display: grid; gap: 2px 18px; grid-template-columns: repeat(auto-fit,minmax(145px,1fr)); list-style: none; margin: 0; padding: 0; }.lc-player-list li { align-items: center; display: grid; font: 14px/18px var(--lc-pixel-font); grid-template-columns: 18px 1fr 20px; min-width: 0; }.lc-player-list li > span:nth-child(2) { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.lc-player-list__head { background: linear-gradient(#9a6642 0 28%,#c98e6d 28% 78%,#68442e 78%); box-shadow: inset 0 0 0 1px rgba(0,0,0,.35); height: 16px; width: 16px; }.lc-player-list__signal { align-items: end; display: flex; gap: 1px; height: 13px; justify-content: flex-end; }.lc-player-list__signal i { background: #555; display: block; height: 3px; width: 2px; }.lc-player-list__signal i:nth-child(2) { height: 5px; }.lc-player-list__signal i:nth-child(3) { height: 7px; }.lc-player-list__signal i:nth-child(4) { height: 9px; }.lc-player-list__signal i:nth-child(5) { height: 11px; }.lc-player-list__signal i.is-on { background: #62c558; box-shadow: 1px 0 #183e15; }
.lc-menu-layer { align-items: flex-start; background: rgba(0,0,0,.55); display: flex; inset: 0; justify-content: center; padding-top: clamp(58px, 13vh, 126px); position: fixed; z-index: 80; }
.lc-game-menu { color: #fff; max-width: min(400px, calc(100vw - 28px)); text-align: center; text-shadow: 2px 2px #202020; width: 100%; }.lc-game-menu h2 { font: 20px/1.2 var(--lc-pixel-font); font-weight: 400; margin: 0 0 clamp(34px,8vh,74px); }.lc-game-menu__buttons { display: grid; gap: 8px; }.lc-game-menu button { background: #777; border: 2px solid #111; box-shadow: inset 2px 2px #aaa, inset -2px -2px #555; color: #fff; cursor: pointer; font: 16px/1 var(--lc-pixel-font); min-height: 40px; padding: 8px 18px; text-shadow: 2px 2px #333; }.lc-game-menu button:hover:not(:disabled), .lc-game-menu button:focus-visible { background: #6b6bb6; box-shadow: inset 2px 2px #9b9be1, inset -2px -2px #3c3c76; outline: 2px solid #fff; }.lc-game-menu button:disabled { color: #aaa; cursor: default; }.lc-game-menu__disconnect { margin-top: 12px; }
.lc-toasts { display: flex; flex-direction: column; gap: 7px; pointer-events: auto; position: absolute; right: 20px; top: 20px; width: min(300px, calc(100vw - 40px)); }
.lc-toast { animation: lc-toast-in .25s ease-out both; appearance: none; background: var(--lc-paper); border: 0; box-shadow: 5px 7px 20px rgba(0,0,0,.3); color: var(--lc-ink); cursor: pointer; display: flex; gap: 11px; padding: 12px 15px; text-align: left; transform: rotate(.35deg); }
.lc-toast__pin { background: var(--lc-moss); border-radius: 50%; box-shadow: 0 1px 2px rgba(0,0,0,.45); height: 8px; margin-top: 3px; width: 8px; }.lc-toast--success .lc-toast__pin { background: var(--lc-moss); }.lc-toast--warning .lc-toast__pin { background: var(--lc-rust); }
.lc-toast strong { display: block; font-size: 11px; letter-spacing: .05em; }.lc-toast small { color: rgba(36,38,31,.66); display: block; font: 9px/1.4 var(--lc-note); margin-top: 3px; }
@keyframes lc-toast-in { from { opacity: 0; transform: translateX(25px) rotate(.35deg); } }
.lc-drawer-layer { align-items: center; background: rgba(8,10,8,.67); backdrop-filter: blur(4px); display: flex; inset: 0; justify-content: center; padding: 28px; position: fixed; z-index: 60; }
.lc-drawer { background-color: #d9cfb3; background-image: linear-gradient(rgba(74,81,59,.075) 1px, transparent 1px), linear-gradient(90deg, rgba(74,81,59,.045) 1px, transparent 1px); background-size: 100% 24px, 24px 100%; border: 1px solid #eee5ce; box-shadow: 0 24px 80px rgba(0,0,0,.55), inset 0 0 0 5px rgba(87,77,49,.13); color: var(--lc-ink); max-height: calc(100vh - 56px); max-height: calc(100dvh - 56px); max-width: 1040px; overflow: auto; position: relative; width: 100%; }
.lc-drawer::before { background: var(--lc-moss); content: ""; height: 7px; left: 0; position: absolute; right: 0; top: 0; }
.lc-drawer__heading { align-items: flex-end; border-bottom: 2px solid rgba(36,38,31,.7); display: flex; justify-content: space-between; margin: 30px 32px 0; padding-bottom: 14px; }.lc-drawer__heading h2 { font-size: clamp(24px, 4vw, 38px); letter-spacing: -.04em; line-height: 1; margin: 5px 0 0; text-transform: uppercase; }.lc-drawer__heading .lc-kicker { color: var(--lc-rust); }
.lc-close { align-items: center; background: none; border: 0; color: var(--lc-ink); cursor: pointer; display: flex; gap: 9px; padding: 5px; }.lc-close span { font: 9px var(--lc-note); letter-spacing: .1em; text-transform: uppercase; }.lc-close kbd { border: 1px solid rgba(36,38,31,.45); box-shadow: 0 2px rgba(36,38,31,.3); font: 10px var(--lc-note); padding: 5px 8px; }
.lc-drawer__body { display: grid; gap: 32px; grid-template-columns: minmax(330px, 1fr) minmax(330px, 1.1fr); padding: 25px 32px 33px; }
.lc-section-rule { align-items: baseline; border-bottom: 1px solid rgba(36,38,31,.28); display: flex; justify-content: space-between; margin-bottom: 13px; padding-bottom: 7px; }.lc-section-rule h3 { font-size: 12px; letter-spacing: .12em; margin: 0; text-transform: uppercase; }.lc-section-rule small { color: rgba(36,38,31,.56); font: 9px var(--lc-note); }
.lc-inventory-grid { background: rgba(36,38,31,.87); border: 4px solid rgba(36,38,31,.18); display: grid; gap: 3px; grid-template-columns: repeat(9, 1fr); padding: 5px; }
.lc-inventory-grid__slot { aspect-ratio: 1; min-width: 0; }.lc-inventory-grid__slot:nth-child(-n+9) { border-bottom-color: var(--lc-amber); }.lc-inventory-grid__slot.is-selected { background: rgba(212,154,69,.18); border-color: var(--lc-amber); }
.lc-inventory-grid .lc-item-glyph__mark { font-size: 17px; }.lc-inventory-grid .lc-item-glyph::before { height: 21px; width: 21px; }.lc-pencil-note { color: rgba(36,38,31,.64); font: italic 10px/1.5 var(--lc-note); margin: 12px 4px 0; transform: rotate(-.4deg); }
.lc-armor-rack { align-items: stretch; background: rgba(36,38,31,.08); border: 1px solid rgba(36,38,31,.18); display: grid; gap: 5px; grid-template-columns: 1fr repeat(4, 48px); margin-top: 12px; padding: 7px; }.lc-armor-rack > div { align-self: center; padding-left: 5px; }.lc-armor-rack > div strong { display: block; font-size: 10px; letter-spacing: .08em; text-transform: uppercase; }.lc-armor-rack > div small { color: rgba(36,38,31,.56); font: 8px var(--lc-note); }.lc-armor-slot { background: rgba(36,38,31,.84); border: 1px solid rgba(36,38,31,.2); color: var(--lc-paper); cursor: pointer; height: 48px; padding: 0; position: relative; }.lc-armor-slot:disabled { cursor: default; opacity: .35; }.lc-armor-slot > span { color: rgba(230,220,193,.45); font: 6px var(--lc-note); left: 3px; position: absolute; text-transform: uppercase; top: 2px; z-index: 2; }.lc-armor-slot .lc-item-glyph { min-height: 46px; }.lc-armor-slot .lc-item-glyph__mark { font-size: 17px; }
.lc-recipe-list { display: flex; flex-direction: column; gap: 6px; }.lc-recipe { align-items: center; appearance: none; background: rgba(255,255,255,.16); border: 1px solid rgba(36,38,31,.17); color: var(--lc-ink); cursor: pointer; display: grid; gap: 10px; grid-template-columns: 26px 1fr auto 46px; min-height: 59px; padding: 8px 9px; text-align: left; transition: background .15s, transform .15s; }.lc-recipe:not(:disabled):hover { background: rgba(255,255,255,.42); transform: translateX(-3px); }.lc-recipe:disabled { cursor: not-allowed; filter: saturate(.4); opacity: .55; }.lc-recipe.is-ready { border-left: 3px solid var(--lc-moss); }
.lc-recipe__number { color: rgba(36,38,31,.46); font: 8px var(--lc-note); }.lc-recipe__output { align-items: center; display: flex; gap: 9px; min-width: 0; }.lc-recipe__output > b { align-items: center; background: color-mix(in srgb, var(--item-color), transparent 75%); border: 1px solid var(--item-color); color: var(--item-color); display: flex; font: 900 19px Georgia, serif; height: 34px; justify-content: center; width: 34px; }.lc-recipe__output strong { display: block; font-size: 11px; letter-spacing: .03em; }.lc-recipe__output small { color: rgba(36,38,31,.56); display: block; font: 8px/1.3 var(--lc-note); margin-top: 2px; }.lc-recipe__ingredients { align-items: center; display: flex; gap: 4px; }.lc-ingredient { align-items: center; background: rgba(36,38,31,.08); display: flex; font: 9px var(--lc-note); gap: 2px; padding: 3px 4px; }.lc-ingredient.is-short { color: var(--lc-rust); text-decoration: line-through; }.lc-ingredient__mark { font: 12px Georgia, serif; }.lc-recipe__arrow { color: rgba(36,38,31,.4); }.lc-recipe__action { border: 1px solid rgba(36,38,31,.35); font: 8px var(--lc-note); letter-spacing: .08em; padding: 6px 4px; text-align: center; }.lc-recipe.is-ready .lc-recipe__action { background: var(--lc-moss); border-color: var(--lc-moss); color: #f1e8ce; }
.lc-drawer-layer { backdrop-filter: none; background: rgba(0,0,0,.55); padding: 14px; }
.lc-inventory-window { background: #c6c6c6; background-image: none; border: 4px solid #111; border-radius: 0; box-shadow: inset 4px 4px #fff, inset -4px -4px #555, 0 18px 56px rgba(0,0,0,.6); color: #3f3f3f; max-height: calc(100dvh - 28px); max-width: 704px; overflow: auto; padding: 20px 24px 18px; width: auto; }
.lc-inventory-window::before { content: none; }
.lc-inventory-titlebar { align-items: center; display: flex; justify-content: space-between; margin-bottom: 13px; }.lc-inventory-titlebar h2 { color: #3f3f3f; font: 18px/1 var(--lc-pixel-font); font-weight: 400; margin: 0; text-shadow: 1px 1px #fff; }.lc-inventory-titlebar .lc-close { color: #3f3f3f; padding: 0; }.lc-inventory-titlebar .lc-close span { font-size: 10px; }.lc-inventory-titlebar .lc-close kbd { background: #8b8b8b; border: 2px solid; border-color: #fff #373737 #373737 #fff; color: #fff; text-shadow: 1px 1px #333; }
.lc-inventory-upper { align-items: stretch; display: grid; gap: 34px; grid-template-columns: 254px 1fr; min-height: 190px; }
.lc-equipment-panel { display: grid; gap: 8px; grid-template-columns: 48px 1fr; position: relative; }.lc-armor-column { display: grid; gap: 0; grid-template-rows: repeat(4,48px); }.lc-inventory-window .lc-armor-slot { background: #8b8b8b; border: 2px solid; border-color: #373737 #fff #fff #373737; height: 48px; opacity: 1; width: 48px; }.lc-inventory-window .lc-armor-slot:disabled { opacity: .48; }.lc-armor-slot__label { color: rgba(255,255,255,.55); font: 9px/1 var(--lc-pixel-font); left: 4px; position: absolute; top: 4px; z-index: 3; }
.lc-player-preview { background: #262626; border: 2px solid; border-color: #373737 #fff #fff #373737; min-height: 192px; overflow: hidden; position: relative; }.lc-player-preview > span { display: block; position: absolute; }.lc-player-preview__head { background: linear-gradient(#593f2e 0 25%,#c28b67 25%); box-shadow: inset 0 0 0 2px rgba(0,0,0,.22); height: 42px; left: calc(50% - 21px); top: 18px; width: 42px; }.lc-player-preview__body { background: #39a3a1; height: 68px; left: calc(50% - 29px); top: 60px; width: 58px; }.lc-player-preview__arm { background: #c28b67; height: 66px; top: 61px; width: 17px; }.lc-player-preview__arm--left { left: calc(50% - 46px); }.lc-player-preview__arm--right { right: calc(50% - 46px); }.lc-player-preview__leg { background: #334d9b; height: 52px; top: 128px; width: 27px; }.lc-player-preview__leg--left { left: calc(50% - 28px); }.lc-player-preview__leg--right { right: calc(50% - 28px); }.lc-armor-score { bottom: 4px; color: #ddd; font: 9px/1 var(--lc-pixel-font); left: 57px; position: absolute; text-shadow: 1px 1px #222; }
.lc-inventory-window .lc-crafting-panel { align-self: center; min-width: 0; }.lc-inventory-window h3 { color: #3f3f3f; font: 14px/1 var(--lc-pixel-font); font-weight: 400; margin: 0 0 8px; text-shadow: 1px 1px #fff; }.lc-inventory-window .lc-crafting-panel > p { color: #555; font: 9px/1.35 var(--lc-pixel-font); margin: 9px 0 0; max-width: 260px; }
.lc-crafting-workspace { align-items: center; display: flex; gap: 16px; }.lc-crafting-grid { display: grid; grid-template-columns: repeat(var(--craft-grid-size),48px); }.lc-crafting-slot,.lc-crafting-result { background: #8b8b8b; border: 2px solid; border-color: #373737 #fff #fff #373737; height: 48px; width: 48px; }.lc-crafting-slot:hover,.lc-crafting-result:not(:disabled):hover { background: #a5a5a5; }.lc-crafting-result:disabled { cursor: default; }.lc-crafting-result.is-ready { box-shadow: 0 0 0 2px rgba(255,255,255,.3); }.lc-crafting-arrow { color: #6a6a6a; font: 34px/1 Arial,sans-serif; text-shadow: 1px 1px #fff; }
.lc-pack-panel { margin-top: 15px; }.lc-inventory-window .lc-inventory-grid { background: transparent; border: 0; display: grid; gap: 0; grid-template-columns: repeat(9,48px); padding: 0; width: 432px; }.lc-inventory-window .lc-inventory-grid__slot { aspect-ratio: auto; background: #8b8b8b; border: 2px solid; border-color: #373737 #fff #fff #373737; height: 48px; width: 48px; }.lc-inventory-window .lc-inventory-grid__slot:nth-child(-n+9) { border-bottom-color: #fff; }.lc-inventory-window .lc-inventory-grid__slot.is-selected { background: #9f9f9f; border-color: #373737 #fff #fff #373737; box-shadow: inset 0 0 0 2px rgba(255,255,255,.75); }.lc-inventory-window .lc-inventory-grid__slot.is-hotbar { margin-top: 12px; }.lc-inventory-window .lc-item-glyph__code { display: none; }.lc-inventory-window .lc-item-glyph::before { height: 31px; width: 31px; }.lc-inventory-window .lc-item-glyph__mark { font-size: 24px; }
.lc-inventory-help { color: #555; display: block; font: 9px/1.35 var(--lc-pixel-font); margin-top: 18px; text-shadow: 1px 1px #fff; }
.lc-cursor-stack { background: #8b8b8b; border: 2px solid rgba(255,255,255,.7); color: #fff; height: 44px; pointer-events: none; position: fixed; width: 44px; z-index: 90; }.lc-cursor-stack .lc-item-glyph { min-height: 44px; }
.lc-furnace-layer { align-items: center; background: rgba(8,10,8,.76); backdrop-filter: blur(4px); display: flex; inset: 0; justify-content: center; padding: 28px; position: fixed; z-index: 65; }
.lc-furnace { background: #c8bea3; border: 1px solid #eee5ce; box-shadow: 0 26px 90px rgba(0,0,0,.64), inset 0 0 0 5px rgba(54,49,39,.18); color: var(--lc-ink); max-height: calc(100vh - 56px); max-height: calc(100dvh - 56px); max-width: 880px; overflow: auto; width: 100%; }
.lc-furnace__header { align-items: end; background: #242620; border-bottom: 5px solid #a35e32; color: var(--lc-paper); display: flex; justify-content: space-between; padding: 24px 28px 19px; }.lc-furnace__header span { color: #d79b5a; font: 9px var(--lc-note); letter-spacing: .14em; text-transform: uppercase; }.lc-furnace__header h2 { font-size: 35px; letter-spacing: -.035em; line-height: 1; margin: 6px 0 0; text-transform: uppercase; }.lc-furnace__header button { background: transparent; border: 1px solid rgba(230,220,193,.35); color: var(--lc-paper); cursor: pointer; font: 9px var(--lc-note); padding: 10px 12px; text-transform: uppercase; }
.lc-furnace__body { display: grid; gap: 25px; grid-template-columns: 210px 1fr; padding: 27px 28px 30px; }.lc-furnace__face { align-self: start; background: #494a42; border: 8px solid #5b5c52; box-shadow: inset 0 0 0 2px rgba(255,255,255,.06), 8px 10px 0 rgba(49,45,36,.16); min-height: 245px; padding: 25px 22px; position: relative; }.lc-furnace__vent { background: repeating-linear-gradient(90deg,#1d1f1b 0 7px,#65665b 7px 10px); display: block; height: 54px; }.lc-furnace__mouth { align-items: end; background: linear-gradient(#1c1d19,#2b1b13 45%,#a84f24); border: 5px solid #30312c; box-shadow: inset 0 -11px 18px rgba(245,137,52,.5); display: flex; gap: 7px; height: 82px; justify-content: center; margin-top: 24px; overflow: hidden; }.lc-furnace__mouth i { animation: lc-furnace-flame .8s ease-in-out infinite alternate; background: #e49a3f; clip-path: polygon(50% 0,100% 100%,0 100%); height: 34px; width: 24px; }.lc-furnace__mouth i:nth-child(2) { animation-delay: -.4s; background: #f0c35a; height: 48px; }.lc-furnace__face > small { color: rgba(230,220,193,.68); display: block; font: 8px var(--lc-note); letter-spacing: .08em; margin-top: 18px; text-align: center; text-transform: uppercase; }
.lc-furnace__recipes { min-width: 0; }.lc-furnace-recipe { align-items: center; background: rgba(255,255,255,.14); border: 1px solid rgba(36,38,31,.2); color: var(--lc-ink); display: grid; gap: 13px; grid-template-columns: minmax(90px,1fr) auto 67px; margin-bottom: 8px; padding: 10px; text-align: left; transition: background .15s,transform .15s; width: 100%; }.lc-furnace-recipe:not(:disabled) { cursor: pointer; }.lc-furnace-recipe:not(:disabled):hover { background: rgba(255,255,255,.4); transform: translateX(-2px); }.lc-furnace-recipe:disabled { cursor: not-allowed; opacity: .5; }.lc-furnace-recipe.is-ready { border-left: 4px solid #a35e32; }.lc-furnace-recipe__name strong { display: block; font-size: 11px; text-transform: uppercase; }.lc-furnace-recipe__name small { color: rgba(36,38,31,.56); display: block; font: 8px var(--lc-note); margin-top: 4px; }.lc-furnace-recipe__flow { align-items: center; display: flex; gap: 7px; }.lc-furnace-slot { background: #292b26; color: var(--lc-paper); display: block; height: 52px; position: relative; width: 52px; }.lc-furnace-slot > small { color: rgba(230,220,193,.5); font: 6px var(--lc-note); left: 3px; position: absolute; text-transform: uppercase; top: 2px; z-index: 2; }.lc-furnace-slot .lc-item-glyph { min-height: 52px; }.lc-furnace-flame { color: #b75b2f; font: 20px Georgia,serif; }.lc-furnace-recipe__action { background: rgba(36,38,31,.08); border: 1px solid rgba(36,38,31,.28); font: 8px var(--lc-note); padding: 8px 4px; text-align: center; }.lc-furnace-recipe.is-ready .lc-furnace-recipe__action { background: #a35e32; border-color: #a35e32; color: #fff0d3; }.lc-furnace__status { color: rgba(36,38,31,.65); font: 9px/1.5 var(--lc-note); margin: 14px 2px 0; min-height: 2.8em; }.lc-furnace__status.is-error { color: var(--lc-rust); }
@keyframes lc-furnace-flame { from { transform: scaleY(.72) translateY(3px); } to { transform: scaleY(1.12); } }
.lc-unsupported { align-items: center; background: var(--lc-charcoal); display: flex; inset: 0; justify-content: center; overflow: hidden; padding: 24px; position: fixed; z-index: 100; }.lc-unsupported__topo { background: repeating-radial-gradient(ellipse at 80% 20%, transparent 0 26px, rgba(168,182,107,.08) 27px 28px, transparent 29px 42px); inset: -30%; position: absolute; transform: rotate(-10deg); }.lc-unsupported__card { background: var(--lc-paper); box-shadow: 12px 14px 0 rgba(102,117,65,.48); color: var(--lc-ink); max-width: 390px; padding: 34px 31px; position: relative; transform: rotate(-1deg); }.lc-unsupported__stamp { border: 1px solid var(--lc-rust); color: var(--lc-rust); font: 9px var(--lc-note); letter-spacing: .12em; padding: 5px 7px; }.lc-unsupported__icon { color: var(--lc-moss); font: 900 44px/1 var(--lc-display); margin-top: 27px; }.lc-unsupported h2 { font-size: 35px; letter-spacing: -.045em; line-height: .95; margin: 13px 0 16px; text-transform: uppercase; }.lc-unsupported p { font: 13px/1.6 var(--lc-note); }.lc-unsupported button { align-items: center; background: var(--lc-ink); border: 0; color: var(--lc-paper); cursor: pointer; display: flex; justify-content: space-between; margin-top: 22px; padding: 13px 16px; width: 100%; }.lc-unsupported small { color: rgba(36,38,31,.55); display: block; font: 9px var(--lc-note); margin-top: 13px; }
@media (max-width: 820px) { .lc-survival-wrap { max-width: calc(100vw - 12px); }.lc-hotbar { grid-template-columns: repeat(9, minmax(0, 1fr)); }.lc-hotbar__slot { height: min(40px, calc((100vw - 20px) / 9)); }.lc-player-list { min-width: min(330px,calc(100vw - 24px)); }.lc-drawer-layer,.lc-furnace-layer { padding: 10px; }.lc-drawer,.lc-furnace { max-height: calc(100vh - 20px); max-height: calc(100dvh - 20px); }.lc-drawer__body,.lc-furnace__body { grid-template-columns: 1fr; }.lc-furnace__face { display: none; }.lc-inventory-grid { grid-template-columns: repeat(9, 1fr); }.lc-drawer__heading { margin-inline: 19px; }.lc-drawer__body,.lc-furnace__body { padding: 20px 19px 25px; }.lc-inventory-window { max-width: calc(100vw - 20px); padding: 17px; }.lc-inventory-upper { gap: 18px; grid-template-columns: 220px 1fr; }.lc-inventory-window .lc-inventory-grid { grid-template-columns: repeat(9,minmax(0,48px)); max-width: 432px; width: 100%; }.lc-inventory-window .lc-inventory-grid__slot { width: 100%; } }
@media (max-width: 560px) { .lc-recipe { grid-template-columns: 22px 1fr 42px; }.lc-recipe__ingredients { grid-column: 2 / 4; }.lc-inventory-upper { grid-template-columns: 1fr; }.lc-equipment-panel { display: none; }.lc-inventory-window .lc-inventory-grid { grid-template-columns: repeat(9,minmax(0,1fr)); }.lc-inventory-window .lc-inventory-grid__slot { height: min(48px,calc((100vw - 62px)/9)); }.lc-crafting-workspace { justify-content: center; }.lc-inventory-window .lc-crafting-panel > p { margin-inline: auto; text-align: center; }.lc-furnace-recipe { grid-template-columns: 1fr auto; }.lc-furnace-recipe__flow { grid-column: 1; grid-row: 2; }.lc-furnace-recipe__action { grid-column: 2; grid-row: 2; } }
@media (prefers-reduced-motion: reduce) { .lc-toast,.lc-furnace__mouth i { animation: none; }.lc-slot, .lc-recipe,.lc-furnace-recipe { transition: none; } }
`;

export function HudStyles() {
  return <style>{HUD_CSS}</style>;
}
