import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { encodeStaticBytes } from "./static-byte-encoding.mjs";

const outputPath = process.argv[2];
if (!outputPath) throw new Error("Pass the generated TypeScript output path.");

const faces = [
  [[1,0,0],[1,1,0],[1,1,1],[1,0,0],[1,1,1],[1,0,1]],
  [[0,0,1],[0,1,1],[0,1,0],[0,0,1],[0,1,0],[0,0,0]],
  [[0,1,0],[0,1,1],[1,1,1],[0,1,0],[1,1,1],[1,1,0]],
  [[0,0,1],[0,0,0],[1,0,0],[0,0,1],[1,0,0],[1,0,1]],
  [[1,0,1],[1,1,1],[0,1,1],[1,0,1],[0,1,1],[0,0,1]],
  [[0,0,0],[0,1,0],[1,1,0],[0,0,0],[1,1,0],[1,0,0]],
] as const;
const glyphs = {
  A: "010101111101101", B: "110101110101110", C: "011100100100011", D: "110101101101110",
  E: "111100110100111", F: "111100110100100", G: "011100101101011", H: "101101111101101",
  I: "111010010010111", J: "001001001101010", K: "101101110101101", L: "100100100100111",
  M: "101111111101101", N: "101111111111101", O: "010101101101010", P: "110101110100100",
  Q: "010101101111011", R: "110101110101101", S: "011100010001110", T: "111010010010010",
  U: "101101101101111", V: "101101101101010", W: "101101111111101", X: "101101010101101",
  Y: "101101010010010", Z: "111001010100111",
  "0": "111101101101111", "1": "010110010010111", "2": "110001111100111", "3": "110001011001110",
  "4": "101101111001001", "5": "111100110001110", "6": "011100111101111", "7": "111001010010010",
  "8": "111101111101111", "9": "111101111001110", "?": "110001010000010", "-": "000000111000000",
  "_": "000000000000111", ".": "000000000000010", " ": "000000000000000",
} as const;

function compress(bytes: Uint8Array): number[] {
  const packed: number[] = [];
  for (let index = 0; index < bytes.length;) {
    const control = packed.length;
    packed.push(0);
    let flags = 0;
    for (let bit = 0; bit < 8 && index < bytes.length; bit += 1) {
      let length = 0;
      let distance = 0;
      for (let source = Math.max(0, index - 4_095); source < index; source += 1) {
        let candidate = 0;
        while (candidate < 18 && index + candidate < bytes.length
          && bytes[source + candidate] === bytes[index + candidate]) candidate += 1;
        if (candidate > length) {
          length = candidate;
          distance = index - source;
        }
      }
      if (length >= 3) {
        flags |= 1 << bit;
        const value = (length - 3) * 4_096 + distance;
        packed.push(value >> 8, value & 255);
        index += length;
      } else packed.push(bytes[index++]);
    }
    packed[control] = flags;
  }
  return packed;
}

const coordinates = new Uint8Array(faces.flat(2));
const fontBytes = new Uint8Array(96 * 2);
const fallback = Number.parseInt(glyphs["?"], 2);
for (let code = 0; code < 96; code += 1) {
  fontBytes[code * 2] = fallback >> 8;
  fontBytes[code * 2 + 1] = fallback & 255;
}
for (const [character, pattern] of Object.entries(glyphs)) {
  const value = Number.parseInt(pattern, 2);
  const code = character.charCodeAt(0);
  fontBytes[code * 2] = value >> 8;
  fontBytes[code * 2 + 1] = value & 255;
}
const coordinatePacked = compress(coordinates);
const fontPacked = compress(fontBytes);
const coordinatePayload = encodeStaticBytes(coordinatePacked);
const fontPayload = encodeStaticBytes(fontPacked);
const source = `// Generated by scripts/generate-render-geometry.ts. Do not hand-edit.\n`
  + `import { decodeStaticBytes } from "../../staticData.ts";\n`
  + `export const BOX_VERTEX_COORDINATES = decodeStaticBytes(${JSON.stringify(coordinatePayload)}, ${coordinates.length});\n`
  + `export const BOX_FACE_SHADES = Object.freeze([0.79,0.68,1,0.52,0.88,0.73] as const);\n`
  + `const fontBytes = decodeStaticBytes(${JSON.stringify(fontPayload)}, ${fontBytes.length});\n`
  + `export const NAMEPLATE_FONT = new Uint16Array(96);\n`
  + `for (let index = 0; index < NAMEPLATE_FONT.length; index += 1) NAMEPLATE_FONT[index] = fontBytes[index * 2] * 256 + fontBytes[index * 2 + 1];\n`;
await writeFile(resolve(outputPath), source);
console.log(JSON.stringify({
  coordinates: coordinates.length,
  coordinatePackedBytes: coordinatePacked.length,
  fontBytes: fontBytes.length,
  fontPackedBytes: fontPacked.length,
  sourceBytes: Buffer.byteLength(source),
}));
