import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { encodeStaticBytes } from "./static-byte-encoding.mjs";

const outputPath = process.argv[2];
if (!outputPath) throw new Error("Pass the generated TypeScript output path.");

const faces = [
  [[1,0,0],[1,1,0],[1,1,1],[1,0,0],[1,1,1],[1,0,1]],
  [[0,0,1],[0,1,1],[0,1,0],[0,0,1],[0,1,0],[0,0,0]],
  [[0,1,0],[0,1,1],[1,1,1],[0,1,0],[1,1,1],[1,1,0]],
  [[0,0,1],[0,0,0],[1,0,0],[0,0,1],[1,0,0],[1,0,1]],
  [[1,0,1],[1,1,1],[0,1,1],[1,0,1],[0,1,1],[0,0,1]],
  [[0,0,0],[0,1,0],[1,1,0],[0,0,0],[1,1,0],[1,0,0]],
] as const;
// Seven 5-bit rows per glyph: compact enough for the fixed batch while much
// closer to the block-game HUD proportions than the former 3×5 shorthand.
const glyphs = {
  A:"01110/10001/10001/11111/10001/10001/10001",B:"11110/10001/10001/11110/10001/10001/11110",
  C:"01111/10000/10000/10000/10000/10000/01111",D:"11110/10001/10001/10001/10001/10001/11110",
  E:"11111/10000/10000/11110/10000/10000/11111",F:"11111/10000/10000/11110/10000/10000/10000",
  G:"01111/10000/10000/10111/10001/10001/01111",H:"10001/10001/10001/11111/10001/10001/10001",
  I:"11111/00100/00100/00100/00100/00100/11111",J:"00111/00010/00010/00010/10010/10010/01100",
  K:"10001/10010/10100/11000/10100/10010/10001",L:"10000/10000/10000/10000/10000/10000/11111",
  M:"10001/11011/10101/10101/10001/10001/10001",N:"10001/11001/10101/10011/10001/10001/10001",
  O:"01110/10001/10001/10001/10001/10001/01110",P:"11110/10001/10001/11110/10000/10000/10000",
  Q:"01110/10001/10001/10001/10101/10010/01101",R:"11110/10001/10001/11110/10100/10010/10001",
  S:"01111/10000/10000/01110/00001/00001/11110",T:"11111/00100/00100/00100/00100/00100/00100",
  U:"10001/10001/10001/10001/10001/10001/01110",V:"10001/10001/10001/10001/10001/01010/00100",
  W:"10001/10001/10001/10101/10101/10101/01010",X:"10001/10001/01010/00100/01010/10001/10001",
  Y:"10001/10001/01010/00100/00100/00100/00100",Z:"11111/00001/00010/00100/01000/10000/11111",
  "0":"01110/10001/10011/10101/11001/10001/01110","1":"00100/01100/00100/00100/00100/00100/01110",
  "2":"01110/10001/00001/00010/00100/01000/11111","3":"11110/00001/00001/01110/00001/00001/11110",
  "4":"00010/00110/01010/10010/11111/00010/00010","5":"11111/10000/10000/11110/00001/00001/11110",
  "6":"01110/10000/10000/11110/10001/10001/01110","7":"11111/00001/00010/00100/01000/01000/01000",
  "8":"01110/10001/10001/01110/10001/10001/01110","9":"01110/10001/10001/01111/00001/00001/01110",
  "?":"01110/10001/00010/00100/00100/00000/00100","-":"00000/00000/00000/11111/00000/00000/00000",
  "_":"00000/00000/00000/00000/00000/00000/11111",".":"00000/00000/00000/00000/00000/00110/00110",
  " ":"00000/00000/00000/00000/00000/00000/00000",
} as const;

function compress(bytes: Uint8Array): number[] {
  const packed: number[] = [];
  for (let index = 0; index < bytes.length;) {
    const control = packed.length;
    packed.push(0);
    let flags = 0;
    for (let bit = 0; bit < 8 && index < bytes.length; bit += 1) {
      let length = 0;
      let distance = 0;
      for (let source = Math.max(0, index - 4_095); source < index; source += 1) {
        let candidate = 0;
        while (candidate < 18 && index + candidate < bytes.length
          && bytes[source + candidate] === bytes[index + candidate]) candidate += 1;
        if (candidate > length) {
          length = candidate;
          distance = index - source;
        }
      }
      if (length >= 3) {
        flags |= 1 << bit;
        const value = (length - 3) * 4_096 + distance;
        packed.push(value >> 8, value & 255);
        index += length;
      } else packed.push(bytes[index++]);
    }
    packed[control] = flags;
  }
  return packed;
}

const coordinates = new Uint8Array(faces.flat(2));
const fontBytes = new Uint8Array(96 * 7);
const fallback = glyphs["?"].split("/").map((row) => Number.parseInt(row, 2));
for (let code = 0; code < 96; code += 1) {
  for (let row = 0; row < 7; row += 1) fontBytes[code * 7 + row] = fallback[row];
}
for (const [character, pattern] of Object.entries(glyphs)) {
  const code = character.charCodeAt(0);
  pattern.split("/").forEach((row, index) => { fontBytes[code * 7 + index] = Number.parseInt(row, 2); });
}
const coordinatePacked = compress(coordinates);
const fontPacked = compress(fontBytes);
const coordinatePayload = encodeStaticBytes(coordinatePacked);
const fontPayload = encodeStaticBytes(fontPacked);
const source = `// Generated by scripts/generate-render-geometry.ts. Do not hand-edit.\n`
  + `import { decodeStaticBytes } from "../../staticData.ts";\n`
  + `export const BOX_VERTEX_COORDINATES = decodeStaticBytes(${JSON.stringify(coordinatePayload)}, ${coordinates.length}, ${coordinatePacked.length});\n`
  + `export const BOX_FACE_SHADES = Object.freeze([0.79,0.68,1,0.52,0.88,0.73] as const);\n`
  + `const fontBytes = decodeStaticBytes(${JSON.stringify(fontPayload)}, ${fontBytes.length}, ${fontPacked.length});\n`
  + `export const NAMEPLATE_FONT = fontBytes;\n`;
await writeFile(resolve(outputPath), source);
console.log(JSON.stringify({
  coordinates: coordinates.length,
  coordinatePackedBytes: coordinatePacked.length,
  fontBytes: fontBytes.length,
  fontPackedBytes: fontPacked.length,
  sourceBytes: Buffer.byteLength(source),
}));
