import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { decodePng } from "./png-rgba.mjs";
import { encodeStaticBytes } from "./static-byte-encoding.mjs";

const [manifestArgument, outputArgument] = process.argv.slice(2);
if (!manifestArgument || !outputArgument) {
  throw new Error("Usage: node scripts/generate-default-player-skin.ts visual-assets.json output.ts");
}

const manifest = JSON.parse(await readFile(resolve(manifestArgument), "utf8")) as Readonly<{
  entities: Readonly<{ player_wide: string }>;
}>;
const image = decodePng(Buffer.from(manifest.entities.player_wide, "base64"));
if (image.width !== 64 || image.height !== 64) throw new Error("Installed default player skin must be 64x64.");

const palette: number[] = [];
const paletteIndexes = new Map<string, number>();
const indexes: number[] = [];
for (let pixel = 0; pixel < image.width * image.height; pixel += 1) {
  const offset = pixel * 4;
  const color = [...image.rgba.subarray(offset, offset + 4)];
  const key = color.join(",");
  let paletteIndex = paletteIndexes.get(key);
  if (paletteIndex === undefined) {
    paletteIndex = palette.length / 4;
    if (paletteIndex > 255) throw new Error("Installed default player skin exceeds 256 colors.");
    paletteIndexes.set(key, paletteIndex);
    palette.push(...color);
  }
  indexes.push(paletteIndex);
}

const decoded = [...palette, ...indexes];
const packed: number[] = [];
for (let index = 0; index < decoded.length;) {
  const control = packed.length;
  packed.push(0);
  let flags = 0;
  for (let bit = 0; bit < 8 && index < decoded.length; bit += 1) {
    let length = 0;
    let distance = 0;
    for (let source = Math.max(0, index - 4_095); source < index; source += 1) {
      let candidate = 0;
      while (candidate < 273 && index + candidate < decoded.length
        && decoded[source + candidate] === decoded[index + candidate]) candidate += 1;
      if (candidate > length) { length = candidate; distance = index - source; }
    }
    if (length >= 3) {
      if (length === 18) length = 17;
      flags |= 1 << bit;
      const value = (Math.min(length, 18) - 3) * 4_096 + distance;
      packed.push(value >> 8, value & 255);
      if (length > 17) packed.push(length - 18);
      index += length;
    } else packed.push(decoded[index++]);
  }
  packed[control] = flags;
}

const payload = encodeStaticBytes(packed);
const source = `// Generated by scripts/generate-default-player-skin.ts from the user-authorized local Minecraft import.\n`
  + `import { decodeStaticBytes } from "../../staticData.ts";\n`
  + `const data = decodeStaticBytes(${JSON.stringify(payload)}, ${decoded.length}, ${packed.length}, true);\n`
  + `export const DEFAULT_PLAYER_SKIN_RGBA = new Uint8Array(16384);\n`
  + `for (let pixel = 0; pixel < 4096; pixel += 1) { const input = data[${palette.length} + pixel] * 4; DEFAULT_PLAYER_SKIN_RGBA.set(data.subarray(input, input + 4), pixel * 4); }\n`;
await writeFile(resolve(outputArgument), source);
console.log(JSON.stringify({ colors: palette.length / 4, decodedBytes: decoded.length, packedBytes: packed.length, sourceBytes: Buffer.byteLength(source) }));
